### ISSUE TITLE
taffybar in Stackage

### ISSUE THREAD

**Issue by clinty** [taffybar/taffybar#141]
please get taffybar into Stackage: currently its dependencies conflict with LTS 4.1

**Comment by IvanMalison** [comment]
This is currently blocked on getting the newest version of dbus into stackage

**Comment by clinty** [comment]
dbus 1.0.1 is in Nightly

**Comment by anarcat** [comment]
i think the point of getting it into stackage is exactly that it makes life easier for downstream packaging, but i'm not an expert. :)

**Comment by clinty** [comment]
It should be fine as long as all those packages are buildable with the rest, and if they aren't it's going to be impossible for Debian to have a taffybar newer than 0.4.6.

**Comment by IvanMalison** [comment]
> It should be fine as long as all those packages are buildable with the rest, and if they aren't it's going to be impossible for Debian to have a taffybar newer than 0.4.6.

@clinty Yeah, but the gi- stuff I think IS in stackage, just with an older version, so unless all of that gets bumped too, I think we're still blocked.

**Comment by IvanMalison** [comment]
@clinty If you would like to try to add taffybar though, you are welcome to do so. You can link to this comment if anyone need verification of ownership blessing.

**Comment by clinty** [comment]
I could do that, but I'd be committing you and not myself to issue resolution.

**Comment by IvanMalison** [comment]
@clinty sure that is fine

**Comment by clinty** [comment]
This is being held up by xmonad{,-contrib} issues.

**Comment by simlu** [comment]
@clinty what's going on? Do you have a link?

**Comment by clinty** [comment]
So at least there's

https://github.com/xmonad/xmonad/issues/155
https://github.com/xmonad/xmonad/issues/170
https://github.com/xmonad/xmonad-contrib/issues/255

**Comment by clinty** [comment]
Word on the street is that a volunteer is needed to cut releases for xmonad and xmonad-contrib

**Comment by anarcat** [comment]
the xmonad issues have been resolved, is there anything else holding this up?

**Comment by IvanMalison** [comment]
@anarcat No, I don't think so. I think there might be a fair amount of stuff we would need to get in to stackage in order for taffybar to get in. Look at all the stuff in extra-deps.

**Comment by IvanMalison** [comment]
@clinty Are you still willing to take this on?

**Comment by IvanMalison** [comment]
Seems like this might be the best way to fix https://github.com/NixOS/nixpkgs/issues/63500 . This might be quite a bit of work because we will need to get a bunch of dependencies into stackage as well. Here is a (possibly incomplete) list of the things we need to get in to stackage:

- [ ] status-notifier-item
- [ ] gtk-strut
- [ ] gtk-sni-tray
- [ ] gi-cairo-connector
- [ ] gi-cairo-render

**Comment by IvanMalison** [comment]
See https://github.com/commercialhaskell/stackage/pull/4630

**Comment by IvanMalison** [comment]
https://github.com/commercialhaskell/stackage/pull/5222
