### ISSUE TITLE
Compiling of taffybar config in a stack based system

### ISSUE THREAD

**Issue by sakshamsharma** [taffybar/taffybar#158]
Preface: I don't use `cabal` and my life is much easier since.

The situation: I have stack's env vars exported into my shell, so I can run taffybar and xmonad simply by typing in xmonad or taffybar, and can compile things as I would, via stack.

The problem: Taffybar tries to compile it's configuration without any `.cabal` or `stack.yaml` file apparently. My system happens to have both `gtk` and `gtk3` installed, and thus my taffybar configuration doesn't build (ambiguous reference).

Any ideas about how I may proceed?

Edit: One possible way that occurs to me is to create a dummy folder and export my env vars to point to that folder instead, which contains just the packages I want to compile it with.

**Comment by IvanMalison** [comment]
@sakshamsharma have you made any progress on this front. Perhaps taffybar should do something similar to what xmonad did with https://github.com/xmonad/xmonad/pull/62

**Comment by IvanMalison** [comment]
This is blocked on willdonnelly/dyre#29

**Comment by IvanMalison** [comment]
(And that issue needs to deal with this):
https://stackoverflow.com/questions/46918693/both-versions-of-the-gtk-package-are-visible-when-running-stack-ghc/46943870#46943870

See my comment https://github.com/travitch/taffybar/pull/237#issuecomment-339561686

**Comment by IvanMalison** [comment]
Also see: https://github.com/commercialhaskell/stack/issues/3338

**Comment by IvanMalison** [comment]
the more I think about this, the more I feel  that it is something of a non issue.

You can use something like

https://hackage.haskell.org/package/stack-run

in conjunction with your .cabal and stack.yaml files (that you will have if you are stack compiling anyway) to run taffybar simply enough.

In a way, it is a better solution because it gets rid of the dyre dependency anyway.

**Comment by IvanMalison** [comment]
> The problem: Taffybar tries to compile it's configuration without any .cabal or stack.yaml file apparently. My system happens to have both gtk and gtk3 installed, and thus my taffybar configuration doesn't build (ambiguous reference).

@sakshamsharma The hack to fix this (for now) is to use the package imports language pragma.

```
{-# LANGUAGE PackageImports #-}
```

And then import any gtk stuff as folows:

```
import qualified "gtk3" Graphics.UI.Gtk as Gtk
import qualified "gtk3" Graphics.UI.Gtk.Abstract.Widget as W
import qualified "gtk3" Graphics.UI.Gtk.Layout.Table as T
```

Alternatively, as mentioned in the comment above, you can use `startTaffybar` instead of `dyreTaffybar` and avoid the automatic recompliation entirely

**Comment by IvanMalison** [comment]
I think that the best approach to this is going to be what I describe in https://github.com/yamadapc/stack-run/issues/16

Basically, the idea is to skip dyre entirely when the user has a stack.yaml and cabal and simply rely on stack to detect the need for recompilation.

**Comment by legrostdg** [comment]
Any update on this?

**Comment by legrostdg** [comment]
`stack` seems to support `run` natively (since 1.9.1)

**Comment by IvanMalison** [comment]
@legrostdg Ahh cool. What we actually need is a library function that is capable of running things in the correct environment. I'll need to look at whether or not stack itself exposes these things.

**Comment by IvanMalison** [comment]
@legrostdg For the time being, though, it should suffice to simply make an executable that goes to the appropriate directory and calls `stack run`

**Comment by IvanMalison** [comment]
Seems like dyre now has stack support, so I'm closing this.
