### ISSUE TITLE
Styling tray manager

### ISSUE THREAD

**Issue by willprice** [taffybar/taffybar#162]
Hi,

Thanks for your awesome work on taffybar! It's a lovely little application.

I'm currently trying to style it, and I'd like to style the tray manager separately from the rest of the bar, so I've been looking into GTK theming. I understand that you're using `EggTrayManager` to implement the tray manager, however trying to style this with `class "*EggTrayManager*" style "my-style"` doesn't style the manager. My understanding is that one can style using `widget`, `class` or `widget_class`, none of which seem to match and style the tray.

What is the best way finding out the widget/class name of the items I'd like to theme (in particular the tray)? I've tried grepping through for widget and class but the string constants I've found haven't produced the desired effect.

Cheers

**Comment by travitch** [comment]
Thanks for the report.  Unfortunately, I've never really had much luck at figuring out the gtk(2) theme system myself.  I thought I understood it at one point, but that seemed to break for a large number of people.

One thing to look at: some login managers start XSettings managers (e.g., gnome-settings-daemon or lxconfig).  These programs seem to have some way to override the gtk theme settings pretty aggressively.  If you have an XSettings manager running, you might try to disable it temporarily to see if any of those classes actually work.

**Comment by willprice** [comment]
Hi @travitch,

Thanks for your swift response.

Good suggestion, I had a fiddle and managed to get the icons in the bar with dark backgrounds (with gaps of light background) but can't seem to reproduce this now, I presume because I'm running `mate-settings-daemon`. Killing the daemon kills MATE. Sadly I'm not sure it's worth the effort, I've already sunk ~3 hours into it!

FWIW I tried running taffybar with the following environment variables set:
GTK_THEME, GTK2_RC_FILES (e.g. `env GTK_THEME=Arc:dark GTK2_RC_FILES=/usr/share/themes/Arc-Dark/gtk-2.0/gtkrc  taffybar`) without any success in overriding the current theme.

Just *one more question*, do you know of any easy way to get the names of the widgets in the bar for theming? I can theme some aspects, and I think if I can be sure of the widget hierarchy then I might have better luck overriding the global rules.

Cheers

**Comment by IvanMalison** [comment]
The widget name is never set for the tray which is why it is difficult to style it
You can do something like this to fix this issue
```
      tray = do
        tray <- systrayNew
        container <- Gtk.eventBoxNew
        Gtk.containerAdd container tray
        Gtk.widgetSetName container "Taffytray"
        Gtk.widgetSetName tray "Taffytray"
        return $ Gtk.toWidget container
```

**Comment by willprice** [comment]
@IvanMalison,

Thanks for this suggestion, I've been playing around with this today and have managed to ditch the many many widget pattern matches and just use a single "Taffbar" widget match after applying your suggestion. I'll tart up my config, and produce a tutorial at some point and post it.

**Comment by willprice** [comment]
Here are my findings:

Out of the following:
```

base[NORMAL]
base[PRELIGHT]
base[ACTIVE]
base[SELECTED]
base[INSENSITIVE]

bg[NORMAL]
bg[PRELIGHT]
bg[ACTIVE]
bg[SELECTED]
bg[INSENSITIVE]

fg[NORMAL]
fg[PRELIGHT]
fg[ACTIVE]
fg[SELECTED]
fg[INSENSITIVE]

base[NORMAL]
base[PRELIGHT]
base[ACTIVE]
base[SELECTED]
base[INSENSITIVE]
```

Only

```
bg[NORMAL]
bg[PRELIGHT]

fg[NORMAL]
fg[PRELIGHT]
```

Are applied

`bg` covers the bar and widget backgrounds in `NORMAL` mode, `PRELIGHT` affects the background colour when the window switcher is clicked, changing the background colour of the current window and the window name being hovered over in the drop down list.

`fg` covers the text color (Note, `text` doesn't seem to style anything) in `NORMAL` mode, `PRELIGHT` again only affects items in the window switcher when clicked with similar behaviour.

![prelight](https://cloud.githubusercontent.com/assets/966205/25270475/be7f1c6e-2678-11e7-86b7-e47c8d8ffaba.png)

The image above uses the following taffybar.rc

```
include "solarized.rc"

style "default" {
    font_name = "Terminus 10"
}

style "light"  = "default" {
# NORMAL: Normal color
# PRELIGHT: Mouse over effects
# ACTIVE: Whilst mouse is pressed
# SELECTED: When text is selected
# INSENSITIVE: For widgets that cannot be used
    bg[NORMAL]        = @base3
    bg[PRELIGHT]      = @base1

    fg[NORMAL]        = @base00
    fg[PRELIGHT]      = @red
}

widget "Taffybar*"                style "light"
```

Here's `solarized.rc`
```
# Solarized colors
gtk_color_scheme = "base03:  #002b36" # (dark)  Background
gtk_color_scheme = "base02:  #073642" # (dark)  Background highlights
gtk_color_scheme = "base01:  #586e75" # (dark)  Comments / Secondary content | (light) Optional emphasized content
gtk_color_scheme = "base00:  #657b83" # (light) Body text / Default code / Primary content
gtk_color_scheme = "base0:   #839496" # (dark)  Body text / Default code / Primary content
gtk_color_scheme = "base1:   #93a1a1" # (dark)  Optional emphasized content | (light) Comments / Secondary content
gtk_color_scheme = "base2:   #eee8d5" # (light) Background highlights
gtk_color_scheme = "base3:   #fdf6e3" # (light) Background
gtk_color_scheme = "yellow:  #b58900"
gtk_color_scheme = "orange:  #cb4b16"
gtk_color_scheme = "red:     #dc322f"
gtk_color_scheme = "magenta: #d33682"
gtk_color_scheme = "violet:  #6c71c4"
gtk_color_scheme = "blue:    #268bd2"
gtk_color_scheme = "cyan:    #2aa198"
gtk_color_scheme = "green:   #859900"
```

**Comment by IvanMalison** [comment]
This tray is now deprecated, and the new SNITray does not have this issue
