### ISSUE TITLE
widget to show the current hostname

### ISSUE THREAD

**Issue by cdepillabout** [taffybar/taffybar#250]
It would be nice if there was a stock widget to show the current hostname.  This can easily be added with something like `commandRunnerNew (60 * 60) "uname" ["--nodename"] "<hostname error>" "red"`, but it would be more convenient if there was a stock widget to do it.

If I sent a PR adding this, would it be accepted?

**Comment by travitch** [comment]
I don't see a reason to not accept it, especially if it can have some useful options.

**Comment by IvanMalison** [comment]
As mentioned in #251, probably best to simply use:

```
commandRunnerNew 60.0 "hostname" [] "failed"
```
