### ISSUE TITLE
Automatically push new docker images when master is updated

### ISSUE THREAD

**Issue by IvanMalison** [taffybar/taffybar#281]
As mentioned here (https://github.com/travitch/taffybar/issues/272#issuecomment-382885652)

**Comment by IvanMalison** [comment]
We'll actually also want to update the separate BASE images that are now used for the builds, now that the base docker file and the actual compilation dockerfile are split

**Comment by IvanMalison** [comment]
@travitch This is becoming quite annoying for me because I have to rebuild the taffybar-base docker image locally every time we have a dependency change (even just a simple version bump) I have to rebuild the base image locally (This shouldn't be necessary in theory, but for some reason, fetching the new package index hangs likely https://github.com/commercialhaskell/stack/issues/774). Normally, I wouldn't mind this that much, but the docker container for taffybar is massive (almost 6GB), and this ends up taking a crazy amount of space on my machines.

I can't make the automatic push happen because you need to have admin access to store secrets with travis.

If you feel really strongly about not making an organization or you just don't want to move the repository (I think that if you do move it, it will automatically redirect), then it would be really helpful if you could make a docker account and encrpyt the credentials for that docker account in travis. I can handle everything else wrt setting up the build.

**Comment by IvanMalison** [comment]
@travitch Hey. Thanks for moving the repository. I still can't seem to create a travis secret. I think it might be because I have the member role only right now.

**Comment by IvanMalison** [comment]
@travitch hmm still seems to be an issue:

```
~/dotfiles/dotfiles/config/taffybar/taffybar master*
$ travis env set DOCKER_USERNAME imalison
not allowed to access environment variables for taffybar/taffybar
```

I think I may need to be made an "owner/admin" to be able to access these

The relevant code is here:
https://github.com/travis-ci/travis.rb/blob/master/lib/travis/cli/env.rb#L18

**Comment by travitch** [comment]
You are already an admin on taffybar/taffybar - I don’t really see any other options for me to toggle

**Comment by IvanMalison** [comment]
@travitch Are you sure? It still says I'm a member rather than an owner. Did you try this? https://help.github.com/articles/changing-a-person-s-role-to-owner/

**Comment by IvanMalison** [comment]
The build is no longer broken because I found a fix to the Updating package index hang here:

https://github.com/commercialhaskell/stack/issues/3830#issuecomment-378751470

As such, this issue is no longer quite as urgent (but it will help us get build times now as more and more dependencies change)

**Comment by PierreR** [comment]
It is quite surprising to have travis CI working on specific dockers. What about using a more classical approach ?

**Comment by PierreR** [comment]
It is quite surprising to have travis CI working on specific dockers. What about using a more classical approach ?
Not sure if this is related but  you would expect `stack-8.0.yaml` to be about the LTS-8 while this is not the case at all. Not sure what 8.0, 8.2, 8.4 are meant to stand for.

**Comment by IvanMalison** [comment]
Plan is to move away from docker and to nix in #434

**Comment by IvanMalison** [comment]
I think keeping docker around will still be useful for testing stack builds

**Comment by IvanMalison** [comment]
#434 is done. I don't really want to maintain docker anymore.
