### ISSUE TITLE
Taffybar fails to build in nixpackages

### ISSUE THREAD

**Issue by PierreR** [taffybar/taffybar#298]
The introduction of `haskell-gi` in v1.0.2 has been a huge change. Indeed `haskell-gi` does not work in `ghc-8.2.x` due to apparently a regression bug in ghc.

IMHO this kind of change need a version bump far greater than the mere third digit ... In nixos for instance, `taffybar` can't be built anymore (as the current default is still ghc-8.2.x).

I guess it is now too late but maybe for next time it would better to mark such changes with a second digit version bump (`1.1.x` in this case). On the other hand, using the latest digit forces everyone to update asap but well.

**Comment by IvanMalison** [comment]
@PierreR haskell-gi does work in ghc-8.2.x . Overloading is broken, but I was careful to avoid overloading. 1.0.2 has an important memory leak bug fix, but otherwise not changes in functionality. It was necessary to use gi-gtk to solve the issue, so I didn't have much choice in the matter, but I still think a point release version bump was the correct move here, since the changes are not backwards incompatible in any way, and no new functionality was introduced.

**Comment by IvanMalison** [comment]
> IMHO this kind of change need a version bump far greater than the mere third digit ... In nixos for instance, taffybar can't be built anymore (as the current default is still ghc-8.2.x).

Are you sure about this? Can you show me the failing build log. I literally just built master with 8.2.2 on my machine.

**Comment by IvanMalison** [comment]
@PierreR IF it really is the case that this fails to build in nix os (using cabal/nix) why not just use stack to build, which will almost certainly work.

**Comment by IvanMalison** [comment]
@PierreR See my comment here:

https://github.com/NixOS/nixpkgs/issues/37724#issuecomment-385268708

I think you may have misidentified the cause of the failed build.

**Comment by PierreR** [comment]
@IvanMalison Thanks for your input.

The `haskell-gi` issue has been fixed. There is a new one specify to taffybar-2.0 that prevents the build to succeed:
https://github.com/IvanMalison/status-notifier-item/issues/1

**Comment by IvanMalison** [comment]
See https://github.com/NixOS/nixpkgs/pull/40186

**Comment by puffnfresh** [comment]
I've submitted https://github.com/haskell-gi/haskell-gi/pull/172 and https://github.com/NixOS/cabal2nix/pull/353. I'm not sure which is the appropriate place to make the change but either should work. Both are better than changes directly in nixpkgs.

**Comment by puffnfresh** [comment]
After getting past haskell-gi, we hit the command line argument limit known issue.

**Comment by puffnfresh** [comment]
I can get past that problem with:

```nix
haskellPackages.taffybar.overrideDerivation (drv: { strictDeps = true; })
```

But there's yet another problem:

```
[ 5 of 65] Compiling System.Taffybar.DBus.Client.UPowerDevice ( src/System/Taffybar/DBus/Client/UPowerDevice.hs, dist/build/System/Taffybar/DBus/Client/UPowerDevice.o )

src/System/Taffybar/DBus/Client/UPowerDevice.hs:1:1: error:
    Exception when trying to run compile-time code:
      dbus-xml/org.freedesktop.UPower.Device.xml: openFile: does not exist (No such file or directory)
    Code: generateClientFromFile
            defaultRecordGenerationParams
              {recordName = Just "BatteryInfo", recordPrefix = "battery",
               recordTypeForName = batteryTypeForName}
            uPowerGenerationParams
            False
            $ "dbus-xml" </> "org.freedesktop.UPower.Device.xml"
```

**Comment by puffnfresh** [comment]
Which is because that file isn't in the Hackage source! https://hackage.haskell.org/package/taffybar-2.1.0/src/

**Comment by puffnfresh** [comment]
https://github.com/taffybar/taffybar/issues/363 already fixed, awaiting a release.

**Comment by IvanMalison** [comment]
@puffnfresh Just published a new release

**Comment by IvanMalison** [comment]
@puffnfresh Any idea how I might leverage strictDeps to fix the stack build, which seems to run in to the same issue?

**Comment by puffnfresh** [comment]
@IvanMalison no sorry, I don't even understand `strictDeps` from nixpkgs but I can just confirm that it fixes the problem.

**Comment by IvanMalison** [comment]
@puffnfresh Hmm I'm actually in the process of migrating to nixOS from arch right now, but I can't get taffybar working at all. Can you share your config maybe?

**Comment by puffnfresh** [comment]
I've got taffybar in my systemPackages:

https://github.com/puffnfresh/nix-files/blob/8d836a60cbf9769af6fab9d8a5632de0a965d5c0/carbon-x1-gen2/configuration.nix#L50

And in my XMonad extraPackages:

https://github.com/puffnfresh/nix-files/blob/8d836a60cbf9769af6fab9d8a5632de0a965d5c0/carbon-x1-gen2/configuration.nix#L73

Then some Taffybar stuff somewhere in my xmonad.hs

**Comment by puffnfresh** [comment]
@IvanMalison I'm currently running something like:

```nix
{
  nixpkgs.config = {
    packageOverrides = super: let self = super.pkgs; in {
      haskellPackages = super.haskellPackages.override {
        overrides = self': super': {
          gi-dbusmenugtk3 = self.haskell.lib.addPkgconfigDepend super'.gi-dbusmenugtk3 self.gtk3;
          taffybar = super'.taffybar.overrideDerivation (drv: {
            strictDeps = true;
            src = self.fetchFromGitHub {
              owner = "taffybar";
              repo = "taffybar";
              rev = "v2.1.1";
              sha256 = "12g9i0wbh4i66vjhwzcawb27r9pm44z3la4693s6j21cig521dqq";
            };
          });
        };
      };
    };
  };
}
```

From nixpkgs master. I've had to work around a few other bugs with master, but this might work for you!

**Comment by IvanMalison** [comment]
@puffnfresh ah I see, you are installing form nixpkgs master.

The strict deps option hasn't even appreared in the unstable channel yet, and I'm not sure I want to switch to using the git master. I suppose it is worth a shot though.

**Comment by PierreR** [comment]
@IvanMalison FWIW you can keep your system on the stable channel and pin to a precise nixpkgs commit to build taffybar. That's what I am doing.

**Comment by IvanMalison** [comment]
@PierreR Cool. I'm new to nix. How exactly do you do that?

**Comment by IvanMalison** [comment]
@PierreR Found some info here: https://nixos.wiki/wiki/FAQ/Pinning_Nixpkgs

**Comment by PierreR** [comment]
@IvanMalison Here is some extra info from my note: http://pierrer.github.io/notebook/#_nix (search for "Pinned a version of nixpkgs"). with recent version of nix `fetchTarball` is usually the way to go.

**Comment by IvanMalison** [comment]
See my comment https://github.com/NixOS/nixpkgs/issues/40013#issuecomment-394254761. I suspect that the latest commits that I have pushed may be getting us close to a solution!

**Comment by PierreR** [comment]
@IvanMalison I have managed to get `taffybar-v2.1.1` up and running on nixos following @puffnfresh recipe and using this pinned info:
```
λ ~ → cat .config/nixpkgs/.nixpkgs.json 
{
  "url": "https://github.com/NixOS/nixpkgs.git",
  "rev": "448d7d648d1a2e8aacc85f9d0abc90643ca2e89b",
  "date": "2018-06-03T13:52:13+02:00",
  "sha256": "04ph82bxms8j9hdx2k9irikzxmg4lqr6vq7h97bgvfgxy4f6ssw7",
  "fetchSubmodules": true
}
```
But I still need to adjust the default UI which is really awful for me. I don't know why it is suddenly so big ;-)
![taffybar](https://user-images.githubusercontent.com/93115/40905979-ca44c4aa-67df-11e8-9f5b-5a896799eea3.png)

**Comment by IvanMalison** [comment]
Are you using the default config? Looks like you have some bar padding. You can turn that off by adjusting the barPadding value in your config.

**Comment by PierreR** [comment]
The lastest nixpkgs is building `taffybar-2.1.1` just fine. Feel free to re-open the issue if necessary.
