### ISSUE TITLE
Support icon theming in window icons in workspaces widget

### ISSUE THREAD

**Issue by katandtonic** [taffybar/taffybar#299]
The icon theme that I've chose doesn't seem to take effect for the workspaces widget.

**Comment by IvanMalison** [comment]
This might be useful https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html

**Comment by IvanMalison** [comment]
https://stackoverflow.com/questions/5810399/how-to-get-icon-icons-path-of-running-app-in-linux-windows

**Comment by IvanMalison** [comment]
I think the best way to approach this is going to be to use https://developer.gnome.org/libwnck/stable/

**Comment by IvanMalison** [comment]
This will likely happen as part of #349. Looks like we need gi-wnck
