### ISSUE TITLE
Calendar doesn't respect color scheme nor gtk-engine 

### ISSUE THREAD

**Issue by ghost** [taffybar/taffybar#3]
First of all, thanks you for taffybar... it's just what i was looking for and it's great :D

The calendar doesn't seem to respect colors of the gtk theme nor the engine rendering, the calendar just looks like the default engine/colors. I tried to workaround this using the taffybar.rc with no results.

As a request, some option to add margins (right and left) cause i think the first and last characters are too close to the edge of the screen.Maybe adding something like pangoColor for the pp :D.

And for documentation purposes add a xmonad.hs example and add how to change the taffybar font maybe good idea.

Best regards Claudio J. Nervi .P

P.D.: using taffybar 0.1.3 from cabal in slackware64 13.37
P.D.2: sorry my bad English, I'm a Spanish speaker

**Comment by IvanMalison** [comment]
can anyone verify that this is still an issue?

@teleshoes ?

**Comment by IvanMalison** [comment]
As travitch mentioned, taffybar intentional ignores and overrides the users gtk theme. Any customizations should be done through the css files in ~/.config/taffybar
