### ISSUE TITLE
time dependency should be updated to >=1.8

### ISSUE THREAD

**Issue by krsch** [taffybar/taffybar#311]
`src/System/Taffybar/Information/Network.hs` imports `Data.Time.Clock.System` which has appeared in time-1.8, but cabal file requires time>=1.4

**Comment by IvanMalison** [comment]
@krsch Ahh good point. I'll update the dependency in hackage.

**Comment by IvanMalison** [comment]
Updated in source and in hackage. 2.0.0 should work now!
