### ISSUE TITLE
cmdline args no longer passed through to taffybar exec

### ISSUE THREAD

**Issue by teleshoes** [taffybar/taffybar#315]
cmdline args to cabal bin `taffybar` used to get passed through to the user's executable (i.e.: user's taffybar.hs `main`).

now i get a usage error. (i use this to put taffybar on the bottom of my screen every 60min to prevent burn-in on my plasma tv. i have workarounds, for instance just using the user exec)

perhaps this could be done explicitly, like `taffybar --log-level DEBUG -- --args --to --user --exec`
or implicitly, like `taffybar --log-level DEBUG --first-non-parseable-arg-gets-sent-to-user-exec`

**Comment by IvanMalison** [comment]
@teleshoes if you need to parse your own command line arguments, I would recommend simply building your own executable. Presumably, you already have your own cabal (and stack?) files in your taffybar directory, correct? All the taffybar executable does is call `dyreTaffybar defaultTaffybarConfig`, and handle that logging argument. I think its fair to assume that any user that is taking custom command line arguments, has a sufficiently advanced configuration/haskell knowledge to be able to handle building their own executable.

**Comment by teleshoes** [comment]
@IvanMalison yea sounds good
i changed my wrapper to just use `~/.cache/taffybar/taffybar-ARCH` when restarting to avoid burn-in

**Comment by IvanMalison** [comment]
@teleshoes Just so you know, the new advanced config could probably do the same thing that your wrapper is doing without forcing a restart of the process.

All you would need to do is write a barconfiggetter
https://github.com/taffybar/taffybar/blob/03b83ba6aba674fc9214d230c9faf2ec6fcb38e7/src/System/Taffybar/Context.hs#L81

that returns the appropriate bar config (depending on the current hour), and calling refreshTaffyWindows on a timer that is run as startup hook
