### ISSUE TITLE
Arch package is out of date

### ISSUE THREAD

**Issue by IvanMalison** [taffybar/taffybar#336]
@LeifW I know that a ton of dependencies have been added, that will make updating the package in the arch repos a chore (Though this is part of why I prefer not to have an arch package in the first place)

Just wanted to note this here so that people know that we are aware of the issue.

Do you think you can get 2.0.0 in the aur any time soon?

**Comment by LeifW** [comment]
Taffybar now depends on gtk3-0.14.9. The version in [community] is currently 0.14.8. I reported it out of date, and version 0.14.9 is currently in [community-testing], so we should see it in [community] soon.
https://www.archlinux.org/packages/community-testing/x86_64/haskell-gtk/

**Comment by IvanMalison** [comment]
@LeifW There's nothing else you need to do? e.g. is gi-libdbusmenu and the like all in there already?

**Comment by dongcarl** [comment]
@IvanMalison @LeifW I believe haskell-gtk got updated recently to 0.14.9, gi-libdbusmenu isn't in AUR or packages yet.

**Comment by IvanMalison** [comment]
@dongcarl yeah, using the arch package isn't recommended at this point. You are much better off using stack ATM

**Comment by LeifW** [comment]
PKGBUILD on AUR upgraded to 2.1.1 by Solomon.
