### ISSUE TITLE
Start status-notifier-watcher automatically in SNITray

### ISSUE THREAD

**Issue by silasdavis** [taffybar/taffybar#355]
Forgive my ignorance - I feel like this ought to be debuggable from this repo (
https://github.com/taffybar/gtk-sni-tray), but I've spent several hours and would just like my taffybar working again

When running with the example config provided here: https://github.com/taffybar/taffybar/blob/master/taffybar.hs.example I get the following error resulting from the use of `sniTrayNew`:

```
MethodError {methodErrorName = ErrorName "org.freedesktop.DBus.Error.ServiceUnknown", methodErrorSerial = Serial 8, methodErrorSender = Just (BusName "org.freedesktop.DBus"), methodErrorDestination = Just (BusName ":1.61"), methodErrorBody = [Variant "The name org.kde.StatusNotifierWatcher was not provided by any .service files"]}
taffybar-linux-x86_64: user error (Pattern match failure in do expression at src/System/Taffybar/Widget/SNITray.hs:31:3-11)
```

I'm running on Arch Linux with systemd and the last time I had to think about dbus I was fairly sure it is being started for me without `dbus-launch`. I'm not sure what the guidance in that repo is trying to do, why KDE comes into this, and what a StatusNotifierWatcher is exactly.

Is there any guidance you can provide on what is needed to get that default config working, is there something I am not running as a separate service?

**Comment by IvanMalison** [comment]
> Forgive my ignorance - I feel like this ought to be debuggable from this repo

@silasdavis No worries this is actually something that comes up quite often because the documentation is not yet clear enough about some details.

Read this: https://github.com/taffybar/gtk-sni-tray#statusnotifierwatcher . Basically, you need to start a StatusNotifierWatcher from https://github.com/IvanMalison/status-notifier-item in order for the tray to work.

I think that I might start starting the watcher automatically, but there are reasons that that is a slightly less than optimal solution.

**Comment by LeifW** [comment]
So, I start [status-notifier-watcher](https://github.com/IvanMalison/status-notifier-item) first so I can start taffybar. It seems I also need to start [xembedsniproxy](https://aur.archlinux.org/packages/xembed-sni-proxy-git/) to get the tray icons to show up.

We might be able to have a systemd DBus service registered at "org.kde.StatusNotifierWatcher" to get systemd to automatically launch "status-notifier-watcher" when requested?

**Comment by IvanMalison** [comment]
> It seems I also need to start xembedsniproxy to get the tray icons to show up.

@LeifW You only need xembedsniproxy if you want xembed tray icons to show up.



> We might be able to have a systemd DBus service registered at "org.kde.StatusNotifierWatcher" to get systemd to automatically launch "status-notifier-watcher" when requested?

There is already a way to start the watcher automatically with the startWatcher parameter to the host params when we start the host object. gtk-sni-tray-standalone does this here:

https://github.com/taffybar/gtk-sni-tray/blob/master/app/Main.hs#L164

we would just need to do the same thing here:

https://github.com/taffybar/taffybar/blob/cb01eff450d4ed9e1aa99d880e05c3cbefaa30bb/src/System/Taffybar/Widget/SNITray.hs#L32

The reason that I haven't done this yet is in the gtk-sni-tray README:

> You can solve this problem by passing the --watcher flag to gtk-sni-tray-standalone, but this is not recommeneded, because many SNI processes do not monitor for new watcher processes, and so may not immediately register when this new watcher is started.

I would generally like to encourage users to run their own watchers at system startup (instead of at taffybar startup) so that any application that provides an indicator gets an opportunity to register at startup.

**Comment by IvanMalison** [comment]
I think the best thing to do might be to make a function:
```
sniTrayThatStartsWatcherEvenThoughThisIsABadWayToDoIt
```

for people that simply don't want to bother setting the watcher up, just so that they are aware that doing so doesn't always behave well.

**Comment by IvanMalison** [comment]
@silasdavis You can now use `sniTrayThatStartsWatcherEvenThoughThisIsABadWayToDoIt` if you don't want to try to figure out how to separately run a watcher process. As the name suggests, this is not the recommeneded way to do it, but should work.



> We might be able to have a systemd DBus service registered at "org.kde.StatusNotifierWatcher" to get systemd to automatically launch "status-notifier-watcher" when requested?

@LeifW That sounds like a good idea, but is kind of a separate issue.

**Comment by silasdavis** [comment]
Thanks for this and the update.

The thing that threw me was the link to the gtk-sni-tray project - it's not that obvious that you are suggesting people just need to run status-notifier-item and not gtk-sni-tray-standalone. That readme suggest you use the gtk-sni-tray widget through taffybar. So then the question is am I meant to run gtk-sni-tray-standalone and connect the two (processes) somehow? I see looking at the taffybar source that gtk-sni-tray code is imported by taffybar so the sense is in code reuse, but you might not otherwise realise you were 'using' gtk-sni-tray at all. Then when you click through to status-notifier-item there are no docs at all, and it's not immediately clear to me it is a binary. A certain level of context is assumed for this project. I probably should have committed to reading the code up front, it's pretty readable and make things clearer as does the freedesktop spec.

Anyway, it's not on you to provide your work for free and then document it, so perhaps this is somewhere I could contribute. I think taffybar (and xmonad for that matter) would benefit from a batteries included, opinionated, markdown-documented fully working set of xinit scripts. Browsing other peoples dotfiles works but a lot of personal stuff is mixed with other far more standard desires. I wonder what this would look like. I also think that some of this is a symptom of the way a lot of us do startup with xinit is a bit wonky...

**Comment by silasdavis** [comment]
Currently running `stack exec status-notifier-item-static &` (which seems to be the binary I get from stack) from my xinitrc or from my xmonad startuphook spawn before taffybar runs gives me the same error as originally reported. I'm using a plain `sniTrayNew` call in my taffybar.hs. Should just running the status-notifier-item work?

**Comment by IvanMalison** [comment]
@silasdavis That is the wrong binary. you need to run status-notifier-watcher

**Comment by IvanMalison** [comment]
status-notifier-item-static is just a sample status-notifier-item so that you can test that your tray is wsowrking.
