### ISSUE TITLE
Workspaces: show window title on hover

### ISSUE THREAD

**Issue by IvanMalison** [taffybar/taffybar#357]

**Comment by pnotequalnp** [comment]
For this are you looking for something more than just adding the title as a GTK tooltip to the window icon?

**Comment by IvanMalison** [comment]
@pnotequalnp I think that is probably fine. This is not an issue that I personally care about, and so I suspect that this feature was requested by someone (maybe in gitter chat?). Does not really seem particularly important tbh.
