### ISSUE TITLE
Segfault on GHC 8.4.{1, 2, 3}

### ISSUE THREAD

**Issue by LeifW** [taffybar/taffybar#358]
```
(gdb) run
Starting program: /home/leif/.cache/taffybar/taffybar-linux-x86_64 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffdb5da700 (LWP 25116)]
[New Thread 0x7fffdadd9700 (LWP 25117)]
[New Thread 0x7fffda5d8700 (LWP 25118)]
[New Thread 0x7fffd9dd7700 (LWP 25119)]
[New Thread 0x7fffcbfff700 (LWP 25120)]
[New Thread 0x7fffcb7fe700 (LWP 25121)]
[New Thread 0x7fffcaffd700 (LWP 25122)]
[New Thread 0x7fffca7fc700 (LWP 25123)]
[New Thread 0x7fffc9ffb700 (LWP 25124)]

Thread 1 "taffybar-linux-" received signal SIGSEGV, Segmentation fault.
0x00007ffff7e779c5 in ?? () from /usr/lib/ghc-8.4.2/rts/libHSrts_thr-ghc8.4.2.so
(gdb) quit
A debugging session is active.

	Inferior 1 [process 25112] will be killed.

Quit anyway? (y or n) y
```

It's enough to change focus between on-screen windows a few times to trigger this.

Tested on current master e38648759d76840e651fb6cd5ccdc5788f2e2559.

GHC 8.4.2, on an Arch system that's up-to-date as of today.

Could be some GHC 8.4 bug? Perhaps some change in assumptions around memory management across the C FFI?

**Comment by IvanMalison** [comment]
@LeifW Can you set log level to DEBUG and run. Might help give us a sense of where things are crashing.

**Comment by LeifW** [comment]
I copied the [logDebug](https://github.com/IvanMalison/dotfiles/blob/master/dotfiles/config/taffybar/taffybar.hs#L90) from your taffybar.hs, and switched focus back and forth between two windows until it crashed:
```
...
Scaling pb to 17, actualW: 16, actualH: 16, scaledW: 17, scaledH: 17
targetW: 17, targetH: 17
Allocating image: size 17, width 17,  height 17, aw: 17, ah: 23, pbw: 17 pbh: 17
Scaling pb to 17, actualW: 128, actualH: 128, scaledW: 17, scaledH: 17
targetW: 17, targetH: 17
Allocating image: zsh: segmentation fault (core dumped)  taffybar
```

**Comment by IvanMalison** [comment]
Hmm: looks like it might be an issue with window images. What happens if you disable window images completely?

**Comment by LeifW** [comment]
Like set `getWindowIconPixbuf` on `WorkspacesConfig` to `const $ const $ pure Nothing`? I tried that, and get no window icons, but it still crashes. I removed "workspaces" entirely, and it still crashes.
I also changed `logDebug` to:
```haskell
logDebug = do
  logger <- getLogger "System.Taffybar"
  saveGlobalLogger $ setLevel DEBUG logger
```

```
Writing info BatteryInfo {batteryNativePath = "", batteryVendor = "", batteryModel = "", batterySerial = "", batteryUpdateTime = 1527653191, batteryType = BatteryTypeBatteryType, batteryPowerSupply = True, batteryHasHistory = False, batteryHasStatistics = False, batteryOnline = False, batteryEnergy = 55.15, batteryEnergyEmpty = 0.0, batteryEnergyFull = 77.38, batteryEnergyFullDesign = 0.0, batteryEnergyRate = 17.675, batteryVoltage = 0.0, batteryLuminosity = 0.0, batteryTimeToEmpty = 11232, batteryTimeToFull = 0, batteryPercentage = 71.0, batteryTemperature = 0.0, batteryIsPresent = True, batteryState = BatteryStateDischarging, batteryIsRechargeable = True, batteryCapacity = 0.0, batteryTechnology = BatteryTechnologyUnknown, batteryWarningLevel = 1, batteryBatteryLevel = 1, batteryIconName = "battery-full-symbolic"}
Allocating image: size 26, width 26,  height 26, aw: 26, ah: 32, pbw: 26 pbh: 26
Allocating image: size 26, width 26,  height 26, aw: 26, ah: 32, pbw: 26 pbh: 26
Battery changed properties: fromList [("SysFSPath",Variant "/sys/devices/pci0000:00/0000:00:02.0/drm/card0/card0-eDP-1/intel_backlight")]
Battery changed properties: fromList [("ActiveEnterTimestamp",Variant 1527646097256818),("ActiveEnterTimestampMonotonic",Variant 3256818),("ActiveExitTimestamp",Variant 0),("ActiveExitTimestampMonotonic",Variant 0),("ActiveState",Variant "active"),("AssertResult",Variant False),("AssertTimestamp",Variant 0),("AssertTimestampMonotonic",Variant 0),("ConditionResult",Variant False),("ConditionTimestamp",Variant 0),("ConditionTimestampMonotonic",Variant 0),("InactiveEnterTimestamp",Variant 0),("InactiveEnterTimestampMonotonic",Variant 0),("InactiveExitTimestamp",Variant 1527646097256818),("InactiveExitTimestampMonotonic",Variant 3256818),("Job",Variant (0, ObjectPath "/")),("StateChangeTimestamp",Variant 1527646097256818),("StateChangeTimestampMonotonic",Variant 3256818),("SubState",Variant "plugged")]
Writing info BatteryInfo {batteryNativePath = "", batteryVendor = "", batteryModel = "", batterySerial = "", batteryUpdateTime = 1527653191, batteryType = BatteryTypeBatteryType, batteryPowerSupply = True, batteryHasHistory = False, batteryHasStatistics = False, batteryOnline = False, batteryEnergy = 55.15, batteryEnergyEmpty = 0.0, batteryEnergyFull = 77.38, batteryEnergyFullDesign = 0.0, batteryEnergyRate = 17.675, batteryVoltage = 0.0, batteryLuminosity = 0.0, batteryTimeToEmpty = 11232, batteryTimeToFull = 0, batteryPercentage = 71.0, batteryTemperature = 0.0, batteryIsPresent = True, batteryState = BatteryStateDischarging, batteryIsRechargeable = True, batteryCapacity = 0.0, batteryTechnology = BatteryTechnologyUnknown, batteryWarningLevel = 1, batteryBatteryLevel = 1, batteryIconName = "battery-full-symbolic"}
Writing info BatteryInfo {batteryNativePath = "", batteryVendor = "", batteryModel = "", batterySerial = "", batteryUpdateTime = 1527653191, batteryType = BatteryTypeBatteryType, batteryPowerSupply = True, batteryHasHistory = False, batteryHasStatistics = False, batteryOnline = False, batteryEnergy = 55.15, batteryEnergyEmpty = 0.0, batteryEnergyFull = 77.38, batteryEnergyFullDesign = 0.0, batteryEnergyRate = 17.675, batteryVoltage = 0.0, batteryLuminosity = 0.0, batteryTimeToEmpty = 11232, batteryTimeToFull = 0, batteryPercentage = 71.0, batteryTemperature = 0.0, batteryIsPresent = True, batteryState = BatteryStateDischarging, batteryIsRechargeable = True, batteryCapacity = 0.0, batteryTechnology = BatteryTechnologyUnknown, batteryWarningLevel = 1, batteryBatteryLevel = 1, batteryIconName = "battery-full-symbolic"}
Allocating image: size 26, width 26,  height 26, aw: 26, ah: 32, pbw: 26 pbh: 26
Allocating image: size 26, width 26,  height 26, aw: 26, ah: 32, pbw: 26 pbh: 26
zsh: segmentation fault (core dumped)  ./taffybar
```

One time it seemed to last longer, and I got this instead of a segfault.
```
taffybar: internal error: evacuate: strange closure type 4693
    (GHC version 8.4.2 for x86_64_unknown_linux)
    Please report this as a GHC bug:  http://www.haskell.org/ghc/reportabug
zsh: abort (core dumped)  ./taffybar
```
Compiling GHC 8.4.3 right now to see if that'll make a difference.

**Comment by IvanMalison** [comment]
The logging you put there still seems to be using images for something. Can you try using a config with like only a clock or something like that?

**Comment by LeifW** [comment]
I can use what was an older version of the included taffybar.hs.example: `startWidgets = [ workspaces, layout, windows, note ], endWidgets = [  clock, mem, cpu, wifi ]` with no crashes. But with either a `batteryIconNew` in there or `textBatteryNew "$percentage$ : $time$"`, I get the segfaults on GHC 8.4.2.

**Comment by IvanMalison** [comment]
Hmm. that's interesting. That suggests that the issue is something on the dbus side of things with the battery. No idea what that could be. Can you try only enabling the logger for the information battery module?

**Comment by LeifW** [comment]
I installed GHC 8.4.3, and can now run taffybar with either the text battery or batteryIconNew, without it crashing.
I'm guessing it was this thing they mentioned in the 8.4.3 release notes:

- A code generation bug resulting in crashing of some programs using UnboxedSums has been fixed [(#15038)](https://ghc.haskell.org/trac/ghc/ticket/15038).

That issue, while not mentioning segfaults, does mention something I saw, "strange closure type". And memory corruption does seem like something that could cause segfaults.

**Comment by IvanMalison** [comment]
@LeifW Ahh, yeah that makes sense. We definitely are using template haskell for the battery stuff, but we AREN't using UnboxedSums AFAIK.

**Comment by IvanMalison** [comment]
Can we close this?

**Comment by LeifW** [comment]
Sure. I expect other people to hit this, though - GHC 8.4.2 is the current version provided by Arch. I've flagged it as out-of-date.
In the meantime, I suppose people using Arch's GHC package can either avoid certain features, install it with a different version of GHC, or run it as e.g. a systemd user service set to auto-restart on crash?

**Comment by LeifW** [comment]
Curiously enough, if I directly launch `$HOME/.cache/taffybar/taffybar-linux-x86_64` (and that file was definitely built with GHC 8.4.3), it segfaults. But if I launch `taffybar` (built with 8.4.3), which in turn launches that file, then it does not segfault.
I'm confused.

**Comment by IvanMalison** [comment]
@LeifW Sounds like a timing/threads thing. I'm assuming this still only happens when you use the battery module, correct?

**Comment by IvanMalison** [comment]
It seems to me that there IS actually a segfault in ghc 8.4 that is unrelated to the battery widget.

People have been commenting #377 about this, but discussion should continue here.

**Comment by PierreR** [comment]
@IvanMalison Thanks for your help. Yep I don't use the battery widget at all (and taffybar is compiled with ghc-8.4.3. Here is my config. Is it certain that the problem is related to ghc-8.4 ? Could we renamed the issue title (GHC 8.4.x instead of GHC 8.4.2) ?

**Comment by PierreR** [comment]
This ticket might be relevant: https://ghc.haskell.org/trac/ghc/ticket/15260

**Comment by IvanMalison** [comment]
> Is it certain that the problem is related to ghc-8.4 ?

I'd say I'm 95% certain this is related to ghc 8.4. It does not seem to happen in 8.2

Does anyone have a consistent repro of this issue. I have seen it, but it generally only happens the first time taffybar is opened after boot or recompilation.

**Comment by cstrahan** [comment]
This also happens with GHC 8.2.2. I've seen the segfault occur within a minute of normal switching spaces, and I can reliably get it to crash within 3 or 4 seconds by creating a couple windows and holding Mod+Tab (e.g. "next window").

Here's the NixOS overlay I'm using:

```nix
  nixpkgs.overlays = [
    (self: super: {
      taffybar =
        let
          inherit (self.haskell.lib) addBuildDepend;
          hpkgs = pkgs.haskell.packages.ghc822.extend (self: super: {
            ListLike = addBuildDepend super.ListLike self.semigroups;
            gi-glib = super.gi-glib.override { haskell-gi-overloading = self.haskell-gi-overloading_0_0; };
            gi-cairo = super.gi-cairo.override { haskell-gi-overloading = self.haskell-gi-overloading_0_0; };
            gi-xlib = super.gi-xlib.override { haskell-gi-overloading = self.haskell-gi-overloading_0_0; };
          });

          taffybar-unwrapped = super.taffybar.override {
            inherit (hpkgs) ghcWithPackages;
          };
        in
          taffybar-unwrapped.overrideAttrs (drv: {
            nativeBuildInputs = drv.nativeBuildInputs or [] ++ [ self.makeWrapper ];
            buildCommand = drv.buildCommand + ''
              sed -i "2iexport GDK_PIXBUF_MODULE_FILE=${pkgs.librsvg.out}/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache" $out/bin/taffybar
            '';
          });
    })
  ];
```

**Comment by IvanMalison** [comment]
@cstrahan Pretty sure THIS particular issue is related to ghc 8.4. Which version of taffybar does this end up using. If it is anything before 3.0.0 then you are encountering a different issue.

**Comment by cstrahan** [comment]
@IvanMalison  I take back what I said above -- I'm guess I somehow was using an old build when I ran into those segfaults, because I've been successfully running taffybar for the past hour or so with the above configuration.

**Comment by LeifW** [comment]
GHC 8.4.4 has been released, which has a fix for memory corruption after FFI calls.
Also, I just switched to GHC 8.6.1 (Arch upgraded their GHC package). I'll see if any crashes happen subsequently (and I'll try re-adding the battery widget).

**Comment by IvanMalison** [comment]
@LeifW Awesome. definitely keep me posted!

**Comment by LeifW** [comment]
I'm running taffybar as a systemd user service, which is nice because it'll restart on crashes like these, but I can also view all the logs of such things. Looks like the last segfault was October 9th, before I upgraded to GHC 8.6.1. It was segfaulting several times a day back then. I re-added the text battery widget, switch and drag windows around, an d no segfaulting.
So I'm guessing it was that ticket, https://ghc.haskell.org/trac/ghc/ticket/14346, fixed in 8.6.1 and 8.4.4.
Perhaps this issue can be closed as "Don't build taffybar with GHC 8.4.1, 8.4.2, or 8.4.3", but someone should probably test with 8.4.4 to confirm. But 8.6.1 seems to be working great.

**Comment by IvanMalison** [comment]
@LeifW Just to be clear, you think this fixes BOTH the battery issue and the more intermittent crashes that were unrelated to the battery?

**Comment by purefn** [comment]
I can confirm that upgrading to ghc 8.4.4 from 8.4.3 has made taffybar **much** more stable. Before it was crashing almost immediately, with or without the battery widget and window icons. I've now had taffybar running for fifteen minutes without a crash with the battery and window icons enabled. I've been switching workspaces and windows rapidly trying to make it crash and it's continued to chug along. With 8.4.3 it was completely unusable, but with 8.4.4 it seems to be viable again! \o/

FWIW I'm running NixOS on the nixos-unstable channel but am using the nixpkgs-unstable channel in my user profile to install taffybar, i.e. it is not installed system wide.

**Comment by LeifW** [comment]
@IvanMalison Yeah, I never really distinguished between those two issues so much, to be honest. On GHC 8.4.1 and 8.4.2, it would crash multiple times per minute with the battery widget, and without, multiple times per day. Now it's back to not crashing period, with or without battery widget. I'm assuming that referenced GHC bug was the issue.
