### ISSUE TITLE
pagerHints import when using stack

### ISSUE THREAD

**Issue by ssbb** [taffybar/taffybar#365]
Hi!

I can't get it working on XMonad side - `System.Taffybar.Support.PagerHints` module not found. Both are installed with stack. Tried installing taffybar with both script (to `.config/taffybar`) and via `stack install taffybar`. Also tried to use same resolver as XMonad installation.

Is this module required at all now? I am new at Haskell and stack specifically. Maybe is there something I can pass to add extra path so it can find taffybar too? 

Thank you!

**Comment by IvanMalison** [comment]
@ssbb Hope that answers your question. If you have any more one off questions like this, feel free to drop in to the gitter channel to taffybar https://gitter.im/taffybar/Lobby.

That's generally a better way to ask questions, since I'm more likely to respond immediately and it doesn't clutter the issue tracker.

**Comment by ssbb** [comment]
@IvanMalison thank you for quick answer and really good explanation 👍 

Yeah, I am installed it via stack using this guide: https://brianbuccola.com/how-to-install-xmonad-and-xmobar-via-stack/

> I actually just include a version of the pagerhints module right in my xmonad 

Thought it have dependencies on taffybar itself but looks like easier approach. Thank you! 👍

**Comment by IvanMalison** [comment]
@ssbb The reason the example posted in the link works is because they clone xmobar into a local repository and explicitly add it to the stack.yaml file they are using. you could do something simialr with taffybar.
