### ISSUE TITLE
Could not load a pixbuf from...

### ISSUE THREAD

**Issue by IvanMalison** [taffybar/taffybar#367]
**Describe the bug**
Taffybar crashes with the following message:
```
Could not load a pixbuf from /org/gtk/libgtk/theme/Adwaita/assets/check-symbolic.svg.
This may indicate that pixbuf loaders or the mime database could not be found.
```

**To Reproduce**
No known repro

**Version information**
2.1.1 installed with stack on NixOS with nix support enabled

**Comment by Infinisil** [comment]
This is a nixpkgs problem, see https://github.com/NixOS/nixpkgs/issues/39493

**Comment by Infinisil** [comment]
Here's my taffybar wrapper: https://github.com/Infinisil/system/blob/8ae3600dee9db833dfe25802ae93d49d16dac985/config/new-modules/x/taffybar/default.nix#L45-L46

**Comment by PierreR** [comment]
@Infinisil Thanks of the link ! Is it something that will land in `nixos-18.09` ? Do you think it would fix the issue I have with [this PR](https://github.com/taffybar/taffybar/pull/415) ? The wrapper works fine with the current stable channel (which is `ghc822`) by default but would fail to load the configuration dynamically in the unstable branch (default is `ghc843`).

**Comment by IvanMalison** [comment]
This is covered by link in FAQ issue.
