### ISSUE TITLE
With multiple monitors, workspace icons jump around to follow focus

### ISSUE THREAD

**Issue by cumber** [taffybar/taffybar#369]
**Describe the bug**

I use two monitors, and switch which workspace is shown on each monitor independently. What appears to be happening is that the set of all applications visible on both monitors (across whichever two workspaces happen to be visible) have their icons shown in the workspace widget as if they were all in the workspace of whichever monitor has the focus.

Applications on workspaces that aren't currently visible on either monitor remain in their own workspaces.

I have taffybar set to show on both monitors, and the jumping is synchronised between both.

**To Reproduce**

1. With two monitors connected, open one app on each monitor.
2. Switch back and forth between them (either with mouse or keyboard shortcuts)
3. The icons for both apps are shown in the same workspace, moving to whichever one has focus

**Expected behavior**

The icon apps to be shown on their current workspace, regardless of which workspace(s) are currently shown on the monitor(s).

This was the behaviour I had in taffybar <= 1.0.

**Version information**

Git revision 72ba688d824f49c24f96a09e91489cd38994b32d, built with nix.

**Comment by IvanMalison** [comment]
On my phone right now, but see #239. I'll give more details in a but, but this actually has to do with xmonads ewmh impl.

**Comment by IvanMalison** [comment]
I fixed the issue in xmonad's ewmh implementation in
https://github.com/xmonad/xmonad-contrib/pull/238

but that change has not yet made it in to a release, so you will need to build xmonad-contrib from source if you want to fix the issue.

**Comment by IvanMalison** [comment]
@cumber I'm going to close this for now, but feel free to hop on the gitter channel if you need more help.

**Comment by cumber** [comment]
Ah, thanks! Sorry I didn't spot the existing issue (I spent ages looking through issues related to icons for another problem I'm having; don't know how I missed it).

**Comment by IvanMalison** [comment]
@cumber Did you fix the other issue? What was it? If it was not obvious, feel free to add to the list of things that should be added to the FAQ in #332

**Comment by cumber** [comment]
The other problem is that taffybar dies when Slack starts up (with a message about the icon not being found in my icon theme). But then I manually start taffybar again and it works (and displays the slack icon). I think it might be #362.

**Comment by IvanMalison** [comment]
@cumber No that sounds more like #367 . I recently added some alternative icon fetch strategies to allow for icon theming. Instead of always using ewmh icons, we now attempt to load them from desktop files and using icon names, which allows icon theming and stuff. If you just want to use ewmhicon retrieval (which is much less likely to crash the process), you should just provide

```
getWindowIconPixbuf = scaledWindowIconPixbufGetter getWindowIconPixbufFromEWMH
```

in you hud config.

I'm basically trying to harden this feature right now, but its tricky. Icons in linux are kind of a mess

**Comment by cumber** [comment]
Hmm, well with that fix applied I don't have an icon at all for Slack, but it doesn't crash.

**Comment by IvanMalison** [comment]
@cumber Yeah IIRC stack doesn't set an ewmh icon.

Did you say that you are installing with nix? You need to make sure that taffybar is getting the XDG_DATA_DIR and GDK_PIXBUF_ICON_LOADER environment variables.

**Comment by cumber** [comment]
Aha! That was the hint I needed. It was my fault; I had an odd setup where slack was installed via my xmonad's startup script's reference to it, but not actually available in my nix profile. Once I had it referenced from my profile as well, the standard $HOME/.nix-profile/share (which Nixos puts in $XDG_DATA_DIR without needing any configuration) contains the slack.desktop file, and taffybar's default icon handling worked fine.

Thanks a lot for helping me out with extra support!

**Comment by IvanMalison** [comment]
@cumber Nice. I should probably add info about icons in nix which are a little idiosycratic.

**Comment by karthikiyengar** [comment]
Small example of adding click functionality to widgets. The basic idea is to wrap a widget with a `GtkEventBox` that allows you to capture actions

```haskell
caff ::
  MonadIO m =>
  -- | Polling interval (in seconds, e.g. 500)
  Double ->
  m Gtk.Widget
caff interval = liftIO $ do
  label <- pollingLabelNew interval showXidlehookInfo
  ebox <- Gtk.eventBoxNew
  Gtk.containerAdd ebox label
  Gtk.eventBoxSetVisibleWindow ebox False
  _ <- Gtk.onWidgetButtonPressEvent ebox caffCallback
  Gtk.widgetShowAll ebox
  Gtk.toWidget ebox
```

The callback receives information about the type of click, which can then be used to perform whatever action you need. Example here:
https://github.com/taffybar/gtk-sni-tray/blob/07a8b24db5245b58ca39ed6c2fd6bac4e51ccc13/src/StatusNotifier/Tray.hs#L340

**Comment by IvanMalison** [comment]
@karthikiyengar cool, but why did you post this to this issue?

**Comment by karthikiyengar** [comment]
@IvanMalison and others - Sorry for the notification spam, it was accidental. I intended to post that to the FAQ.
