### ISSUE TITLE
XDG Menu: Does not read /etc/xdg unless specified

### ISSUE THREAD

**Issue by ARR8** [taffybar/taffybar#371]
**Describe the bug**
Unlike the description in the comments of the source file, the XDG menu widget seems to only search in /etc/xdg if it is manually specified in XDG_CONFIG_DIRS. Otherwise, there is an error that .config/menus/PREFIX-applications.menu does not exist, but it does not look further.

**To Reproduce**
Unset the XDG_CONFIG_DIRS environment variable and launch taffybar with the XDG menu.

**Expected behavior**
Following the XDG spec, check /etc/xdg even if nothing is specified.

**Screenshots**

**Version information**
Using latest version at time of writing, 72ba688
Installed via stack
Gtk version: 3.22.29+60+ge42d8598ca

Ping @u11gh

**Comment by u11gh** [comment]
I will see to it.

**Comment by u11gh** [comment]
I can reproduce the reported behaviour:  IF XDG_CONFIG_DIRS is set then
/etc/xdg is not searched for a menu file.

This appears to comply with the XDG specs, see
https://specifications.freedesktop.org/basedir-spec/latest/ar01s03.html

I propose to update the doc string of menuWidgetNew from

    ... XDG_CONFIG_DIRS and "/etc/xdg".

to

    ... XDG_CONFIG_DIRS if it is set and not empty and "/etc/xdg"
    otherwise.

**Comment by ARR8** [comment]
My XDG_CONFIG_DIRS is not set and the widget does not look in /etc/xdg regardless. XDG_CONFIG_HOME is the only relevant variable set.

**Comment by u11gh** [comment]
Sorry, I mixed that up.

You are right: if XDG_CONFIG_HOME is set then XDG Menu will not search
in /etc/xdg.  This is wrong.  I shall fix it.

**Comment by u11gh** [comment]
@IvanMalison Please re-open this bug report.  009b741 handled an issue
regarding XDG_CONFIG_DIRS.  The XDG_CONFIG_HOME issue is still open.
I'm working on it now.

Sorry for the confusion.

**Comment by ARR8** [comment]
Confirmed fixed, thanks.
