### ISSUE TITLE
XDG Menu: Locale mostly ignored

### ISSUE THREAD

**Issue by ARR8** [taffybar/taffybar#372]
**Describe the bug**
With a non-English locale set, XDG menu does not localize the category names and only a few of the program names, despite many more of the programs having translations for the locale. This happens with multiple languages.

**To Reproduce**
Launch taffybar with the LANG variable changed and XDG menu enabled.

**Expected behavior**
The category names and all available program names should be localized.

**Screenshots**

**Version information**
Using latest version at time of writing, 72ba688
Installed via stack
Gtk version: 3.22.29+60+ge42d8598ca

Ping @u11gh

**Comment by u11gh** [comment]
I am using xdg menu on a daily basis in a german environment on a debian
testing system without such problems.  Just installed and tried other
locales and things appear to work correctly.

Could you please try other menus, like gnome, mate, xfce?

**Comment by ARR8** [comment]
Trying another menu file fixed the problem. For future reference, Arch seems to localize better when using the arch-applications menu file, though you lose the settings category in selecting it.

**Comment by IvanMalison** [comment]
@ARR8 Not sure I understand what the fix was. Would it be worth documenting the issue in the FAQ

(which doesn't exist yet, but I'm just trying to keep track of stuff in https://github.com/taffybar/taffybar/issues/332)

**Comment by ARR8** [comment]
Not really, it's pretty Arch-specific and honestly something I should have known. Users using taffybar inside a DE won't have this problem, anyway.

**Comment by IvanMalison** [comment]
> Users using taffybar inside a DE won't have this problem,

 I would guess that 80% of taffybar users use XMonad (i.e. not a DE). A significant chunk are also on arch. Your call though.
