### ISSUE TITLE
XDG Menu: Icons not displayed

### ISSUE THREAD

**Issue by ARR8** [taffybar/taffybar#373]
**Describe the bug**
When launching, taffybar complains of not being able to find the icons for several programs. However, no icon is displayed for any program, even the ones about which there is no error. This happens with both default/index.theme inherits=Adwaita and inherits=hicolor, the latter being where the program icons are. 

**To Reproduce**
See above

**Expected behavior**
Icons displayed next to categories and programs.

**Screenshots**

**Version information**
Using latest version at time of writing, 72ba688
Installed via stack
Gtk version: 3.22.29+60+ge42d8598ca

Ping @u11gh

**Comment by u11gh** [comment]
If xdg menu cannot find an icon that is specified in the menu file then
it should complain about it.  So, maybe the icon data are missing from
the  menus.  Could you please try another menu?

**Comment by IvanMalison** [comment]
@ARR8 what distro are you on

**Comment by ARR8** [comment]
Arch. Trying another menu does not fix the problem. Other XDG-displaying programs do have icons.

**Comment by u11gh** [comment]
I can reproduce the reported behaviour: When taffybar is started in a
"plain" X session then most icons will be missing.  They appear as soon as
'mate-settings-daemon' is started.  (Probably works also with the
respective gnome thing.)

Going to check why that happens.

**Comment by IvanMalison** [comment]
Ah yes. I use xsettingsd. That's a good choice for tiling wms. We should put something in the FAQ issue about this

**Comment by u11gh** [comment]
Agree, that should definitely go in the FAQ.

@ARR8 can you confirm that icons appear after starting xsettingsd (or
gnome-settings-daemon or some such)?

**Comment by IvanMalison** [comment]
@ARR8 Do you use the gtk3 or qt version of that application?

**Comment by ARR8** [comment]
GTK3, as mentioned

**Comment by IvanMalison** [comment]
@ARR8 PCManFM is gtk 2.0, I think that a settings daemon is required for certain functionality in gtk3 if you are not using a desktop environment.

**Comment by IvanMalison** [comment]
Specifically, the picking up of the settings in the gtk config files don't work for me in gtk3 without an xsettings daemon

**Comment by ARR8** [comment]
I should mention I am using [a GTK3 version](https://www.archlinux.org/packages/community/x86_64/pcmanfm-gtk3/) of the program. I do have the theme and icon theme specified in the GTK3 config file, which it seems to pick up. I've just confirmed this by switching from Adwaita to Breeze and back. It's possible that the theme selection is not ideal this way, e.g. it doesn't recognize setting the theme to `default`, unlike Qt, and falls back to Adwaita, but everything else works.

**Comment by u11gh** [comment]
Put the following in ~/.config/gtk-3.0/settings.ini

    [Settings]
    gtk-fallback-icon-theme = gnome
    gtk-icon-theme-name = Adwaita
    gtk-menu-images = 1

with theme names of your liking.  Important is the last line which
enables display of icons in menus.

I propose to add this to the FAQ as well and then close this issue,
after it has been verified.

@ARR8 Could you please try this out and confirm that this works for you?

**Comment by ARR8** [comment]
That fixed it. There's now icons everything except categories, which seem to look for icons prefixed with gnome-, and I have none. I agree that this would be a good addition to the FAQ.
