### ISSUE TITLE
Windows widget: HTML de-encoded in menu label but not active label

### ISSUE THREAD

**Issue by ARR8** [taffybar/taffybar#379]
**Describe the bug**
Not sure if this is a known problem. Doesn't seem to be in the docs about the window widget.  
A window title with HTML-encoded characters shows up normally in the active label, but changes to HTML in the window list, in some cases expanding the width dramatically.

**To Reproduce**
Open a program with such characters in the title.

**Expected behavior**
Menu label same as active label.

**Screenshots**
![screenshot2](https://user-images.githubusercontent.com/8064135/41384369-dbe26afa-6f64-11e8-8001-385289047e1b.png)

**Version information**
Latest version, afbe492
Installation method (nix/stack/cabal/arch packages): Stack
Gtk version: 3.22.29+60+ge42d8598ca

**Comment by IvanMalison** [comment]
Hmmm not sure what this could be. Both default markup functions escape markup in the same way so its not clear to me what would be causing this.

**Comment by ARR8** [comment]
Maybe something with GTK itself?

**Comment by IvanMalison** [comment]
@ARR8 Is this still an issue @Tordek changed the way things are escaped.

**Comment by ARR8** [comment]
Yes, this is still an issue

**Comment by IvanMalison** [comment]
@iamjamestl This is fixed now, correct?

@ARR8 Can you verify?

**Comment by iamjamestl** [comment]
@IvanMalison, the window widget has been working for me as expected since #418 was merged.
