### ISSUE TITLE
quick-start.sh no longer works

### ISSUE THREAD

**Issue by licquia** [taffybar/taffybar#380]
**Describe the bug**

quick-start.sh fails to build taffybar with an error:

    Configuring gi-gdkx11-3.0.2...
    setup: The pkg-config package 'gdk-x11-3.0' version >=3.22 is required but the
    version installed on the system is version 3.18.9

**To Reproduce**

Clone the git repository, and then run quick-start.sh from the root of the directory.

**Expected behavior**

The build should succeed.

**Version information**

```
jeff@jeffpc:~/software/taffybar$ git status
HEAD detached at v2.1.2
nothing to commit, working directory clean
jeff@jeffpc:~/software/taffybar$ stack --version
Version 1.7.1, Git revision 681c800873816c022739ca7ed14755e85a579565 (5807 commits) x86_64 hpack-0.28.2
jeff@jeffpc:~/software/taffybar$ stack ghc -- --version
The Glorious Glasgow Haskell Compilation System, version 8.2.2
jeff@jeffpc:~/software/taffybar$ lsb_release -d
Description:	Ubuntu 16.04.4 LTS
jeff@jeffpc:~/software/taffybar$ for pkg in libgirepository1.0-dev libwebkit2gtk-4.0-dev libgtksourceview-3.0-dev; do apt-cache policy $pkg; done
libgirepository1.0-dev:
  Installed: 1.46.0-3ubuntu1
  Candidate: 1.46.0-3ubuntu1
  Version table:
 *** 1.46.0-3ubuntu1 500
        500 http://archive.ubuntu.com/ubuntu xenial/main amd64 Packages
        100 /var/lib/dpkg/status
libwebkit2gtk-4.0-dev:
  Installed: 2.20.2-0ubuntu0.16.04.1
  Candidate: 2.20.2-0ubuntu0.16.04.1
  Version table:
 *** 2.20.2-0ubuntu0.16.04.1 500
        500 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages
        100 /var/lib/dpkg/status
     2.10.9-1ubuntu1 500
        500 http://archive.ubuntu.com/ubuntu xenial/main amd64 Packages
libgtksourceview-3.0-dev:
  Installed: 3.18.2-1
  Candidate: 3.18.2-1
  Version table:
 *** 3.18.2-1 500
        500 http://archive.ubuntu.com/ubuntu xenial/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by IvanMalison** [comment]
@licquia quick-start does not currently handle installing the pkg-config packages that you need to get things working.

You'l need to have everything that is required for haskell-gi plus a few other extras

gdk-x11
libdbusmenu-gtk

I would love to have these things included in quick-start, but its just too hard of a problem to solve because the way you get these packages varies from distro to distro

**Comment by IvanMalison** [comment]
@licquia I'm going to close this for now, since I'm not really sure how we would address it.
