### ISSUE TITLE
 g_param_spec_unref: assertion 'G_IS_PARAM_SPEC (pspec)' failed

### ISSUE THREAD

**Issue by IvanMalison** [taffybar/taffybar#384]
**Describe the bug**
Taffybar crashes

**To Reproduce**
Unknown

Stack, taffybar 2.1.3

**Comment by Tordek** [comment]
Could this one also be because of #231? I had gotten a couple different, seemingly unrelated crashes, at least one being an assertion failure.

**Comment by IvanMalison** [comment]
Yes, it is quite likely this was #231. #231 caused heap corruption which would often not directly cause a crash, only to cause issues later, so it may ifested as several different issues.

**Comment by IvanMalison** [comment]
Closing as related to #231. Will reopen if seen again.
