### ISSUE TITLE
High Idle CPU Usage In Clock Widget With Short Polling TIme

### ISSUE THREAD

**Issue by IvanMalison** [taffybar/taffybar#385]
Taffybar idles at very high cpu usage rates. Sometimes even above 10%.

My investigation indicates that the Text CPU widget is to blame, but @bgamari seems to think it might be ewmh X11 events:

See xmonad/xmonad-contrib#227 and xmonad/xmonad-contrib#263

**Comment by bgamari** [comment]
To be clear, I don't believe there is a single cause for Taffybar's high CPU usage. My observations in xmonad/xmonad-contrib#227 suggest that excessive EWMH property updates contribute. However, as I said in my last comment on that ticket, I don't believe this is the end of the story.

However, I can rule out the Text CPU widget in my case as I don't use it. My configuration (which can be found in https://github.com/bgamari/xmonad-config/blob/master/taffybar-ben/taffybar.hs) only uses the battery icon, clock, SNI tray, MPRIS2, workspace switcher, and XMonad layout widgets. Regardless, I still see high CPU usage (around 20% percent while switching workspaces at the rate of a few times per second; around 2-3% when idle).

**Comment by IvanMalison** [comment]
If you are having issue with idle cpu usage and you use the clock widget, it is recommended that you switch your time config to something like:

https://github.com/ivanmalison/dotfiles/blob/cdb1afc6ab5d4f1ed68fdf5858b6319457adbe94/dotfiles/config/taffybar/taffybar.hs#L147
