### ISSUE TITLE
example code in haddocks does not compile

### ISSUE THREAD

**Issue by cdepillabout** [taffybar/taffybar#386]
There is an example of how to use taffybar in the haddocks on Hackage.

Unfortunately this does not compile anymore:

https://hackage.haskell.org/package/taffybar-2.1.1/docs/System-Taffybar.html

It would be nice if this were kept up to date.

**Comment by IvanMalison** [comment]
@cdepillabout Isn't that an old version of the docs?

**Comment by cdepillabout** [comment]
Yes, but the most recent version of the docs haven't been generated on hackage:

https://hackage.haskell.org/package/taffybar-2.1.2

Also, I could be incorrect, but the errors I was getting didn't seem like they would be fixed by a minor version bump.
