### ISSUE TITLE
weatherNew is not in MonadIO

### ISSUE THREAD

**Issue by Magicloud** [taffybar/taffybar#388]
**Describe the bug**
From sources under `taffybar/src/System/Taffybar/Widget/`, I saw the return types of wNew functions are TaffyIO w, IO w, MonadIO m => m w. Not only they look different. It breaks taffybar example.

**To Reproduce**
Put taffybar.hs.example as ~/.config/taffybar.hs. Restart taffybar to compile. Got error:
```
.config/taffybar/taffybar.hs:42:43: error:
    • Couldn't match type ‘IO Graphics.UI.Gtk.Types.Widget’
                     with ‘Control.Monad.Trans.Reader.ReaderT
                             System.Taffybar.Context.Context IO Graphics.UI.Gtk.Types.Widget’
      Expected type: System.Taffybar.Context.TaffyIO
                       Graphics.UI.Gtk.Types.Widget
        Actual type: IO Graphics.UI.Gtk.Types.Widget
    • In the expression: wea
      In the ‘endWidgets’ field of a record
      In the first argument of ‘simpleTaffybar’, namely
        ‘defaultSimpleTaffyConfig
           {startWidgets = [workspaces, layout, windows, ....],
            endWidgets = [tray, wea, clock, ....]}’
   |
42 |                    , endWidgets = [ tray, wea, clock, mem, cpu, mpris ]
   |                                           ^^^
```

**Expected behavior**
Taffybar starts.

**Screenshots**
N/A

**Version information**
Taffybar version (or git sha if building from source): 2.1.2
Installation method (nix/stack/cabal/arch packages): cabal
Gtk version: 3.22.30

**Comment by IvanMalison** [comment]
`MonadIO m => m w` is a polymorphic type which can be interpreted as any Monad which implements the MonadIO interface so TaffyIO w and that type are compatible.

Looks like I may have missed the weather widget when I changed the type of the widgets, but you can fix it easily by simply applying

liftIO to the return value.

I'll fix this now.
