### ISSUE TITLE
Crash with error message.

### ISSUE THREAD

**Issue by Magicloud** [taffybar/taffybar#398]
**NOTE: If your issue is really a support request, please use the gitter channel to ask it instead of filing an issue https://gitter.im/taffybar/Lobby (REMOVE THIS IF NOT).**

**Describe the bug**
I have not figured out how to trigger this. Taffybar just crashed suddenly. And I saw message in .xsession-errors
```
ErrorEvent {ev_type = 0, ev_display = Display 0x0000000005284c00, ev_serialnum = 256301, ev_error_code = 3, ev_request_code = 20, ev_minor_code = 0, ev_resourceid = 35651589}
Got error
ErrorEvent {ev_type = 0, ev_display = Display 0x0000000005284c00, ev_serialnum = 256302, ev_error_code = 3, ev_request_code = 20, ev_minor_code = 0, ev_resourceid = 35651595}
Got error
ErrorEvent {ev_type = 0, ev_display = Display 0x0000000005284c00, ev_serialnum = 290598, ev_error_code = 9, ev_request_code = 14, ev_minor_code = 0, ev_resourceid = 29370061}
Got error on X11 thread
```
Not sure the "ErrorEvent" is related.

**To Reproduce**
Not sure.

**Expected behavior**
No crashing.

**Screenshots**
N/A

**Version information**
Taffybar version (or git sha if building from source): 2.1.2
Installation method (nix/stack/cabal/arch packages): Cabal
Gtk version: 3.22.30

**Comment by IvanMalison** [comment]
Taffybar will almost always survive those error messages. Are your running off of the absolute latest version (from late yesterday)? If not, you are likely hitting #231 which was just fixed

**Comment by IvanMalison** [comment]
It looks like you are running form 2.1.2, if so I suspect that this is simply #231, I'm going to close for now, but feel free to reopen if you see this on master.

**Comment by Magicloud** [comment]
Pulled the latest source from github and installed. Crashed in 5 mins. I saw some logs in other issues, wondering how could I get something like that?

**Comment by IvanMalison** [comment]
Can you run with gdb?

**Comment by IvanMalison** [comment]
@Magicloud when you say that you installed, can you mention what you installed with?

**Comment by IvanMalison** [comment]
and can you post your config?

**Comment by Magicloud** [comment]
Latest source installed with cabal, ghc 8.4.3.
.config/traffybar/traffybar.hs
```
{-# LANGUAGE OverloadedStrings #-}

module Main where

import Control.Monad.IO.Class
import           System.Taffybar
import           System.Taffybar.Information.CPU
import           System.Taffybar.Information.Memory
import           System.Taffybar.SimpleConfig
import           System.Taffybar.Widget
import           System.Taffybar.Widget.Generic.PollingGraph

memCallback = do
  mi <- parseMeminfo
  return [memoryUsedRatio mi]

cpuCallback = do
  (userLoad, systemLoad, totalLoad) <- cpuLoad
  return [totalLoad, systemLoad]

main = do
  let memCfg = defaultGraphConfig
               { graphDataColors = [(1, 0, 0, 1)]
               , graphLabel = Just "mem"
               }
      cpuCfg = defaultGraphConfig
               { graphDataColors =
                   [ (0, 1, 0, 1)
                   , (1, 0, 1, 0.5)
                   ]
               , graphLabel = Just "cpu"
               }
  let clock = textClockNew Nothing "<span fgcolor='orange'>%a %b %_d %H:%M</span>" 1
      workspaces = workspacesNew defaultWorkspacesConfig
      windows = windowsNew defaultWindowsConfig
      layout = layoutNew defaultLayoutConfig
      note = notifyAreaNew defaultNotificationConfig
--      wea = liftIO $ weatherNew (defaultWeatherConfig "KMSN") 10
      mpris = mpris2New
      mem = pollingGraphNew memCfg 1 memCallback
      cpu = pollingGraphNew cpuCfg 0.5 cpuCallback
      tray = sniTrayNew
  simpleTaffybar defaultSimpleTaffyConfig
    { startWidgets = [ workspaces, layout, windows, note ]
    , endWidgets = [ tray, clock, mem, cpu, mpris ]
    , barHeight = 24
    }
```

**Comment by Magicloud** [comment]
I am not quite familiar with GDB.

**Comment by IvanMalison** [comment]
ghc >= 8.4 is not currently tested

See #358, #377

to run gdb (install it with whatever pm you use) then run 

gdb taffybar

and cause the segfault. This will drop you in to a repl where you can type `where` to get a backtrace
