### ISSUE TITLE
Taffybar crashes when window requires icon that is not found in icon theme

### ISSUE THREAD

**Issue by IvanMalison** [taffybar/taffybar#403]
Errors will look like:

```
taffybar: Icon 'audio-volume-medium' not present in theme breeze (0)
```

Setting 

```
getWindowIconPixbuf = scaledWindowIconPixbufGetter getWindowIconPixbufFromEWMH
```

in WorkspacesConfig can circumvent this issue for now, but we should find a better long term fix.

**Comment by IvanMalison** [comment]
@qrilka Are you using nixos?

**Comment by qrilka** [comment]
Nope, Gentoo

**Comment by IvanMalison** [comment]
This is not actually fixed yet, since we havent required the relevant gtk-sni-tray issue in taffybar

**Comment by IvanMalison** [comment]
Also, the fix in taffybar/gtk-sni-tray@4c46266 only prevents crashes, doesn't really solve the underlying issue bc the icon will still not be visible.

Also, we have other uses of icon loading in taffybar itself that need to be handled.

**Comment by IvanMalison** [comment]
The nixos specific solution to this may be https://github.com/nixos/nixpkgs/blob/e3afc85cbaf57637f829712f338aa12eff2f253a/nixos/modules/config/gtk/gtk-icon-cache.nix#L15

gtk.iconCache.enable = true;

and making sure to install icon packages as part of the system config.

**Comment by NickHu** [comment]
@IvanMalison Having implemented your workaround and then installing every icon package under the sun (`gnome3.adwaita-icon-theme` `gnome2.gnome_icon_theme` `hicolor-icon-theme` `breeze-icons`) under both `systemPackages` and in my user environment, I'm still getting errors like

```
[WARNING] StatusNotifier.Tray - Got null pixbuf for info ItemInfo {itemServiceName = BusName ":1.161", itemServicePath = ObjectPath "/org/ayatana/NotificationItem/nm_applet", itemId = Just "nm-applet", itemStatus = Just "Active", itemCategory = Just "SystemServices", itemToolTip = Nothing, iconTitle = "Network", iconName = "nm-signal-75", overlayIconName = Nothing, iconThemePath = Just "", iconPixmaps = [], overlayIconPixmaps = [], menuPath = Just (ObjectPath "/org/ayatana/NotificationItem/nm_applet/Menu")}
```

Any ideas on what can be done to fix this with NetworkManager applet? Am I missing something?

I'd also like to mention that I get errors from `xembed`ded tray icons (using `xembed-sni-proxy`), particularly with ibus, whereby the dropdowns are buggy/buttons don't work and lots of black artifacting (some of this can be mitigated by restarting `xembed-sni-proxy`). I wonder if it's related to the many errors taffybar spews of the form

```
[ERROR] StatusNotifier.Host.Service - Property update failures [MethodError {methodErrorName = ErrorName "org.freedesktop.DBus.Error.UnknownProperty", methodErrorSerial = Serial 921, methodErrorSender = Just (BusName ":1.166"), methodErrorDestination = Just (BusName ":1.162"), methodErrorBody = [Variant "Property org.kde.StatusNotifierItem.ToolTip was not found in object /StatusNotifierItem"]}]
```

Maybe this should go in a new issue.

**Comment by IvanMalison** [comment]
> Maybe this should go in a new issue.

Yes, that is for another issue. I've actually never been able to get xembed menus to work at all (it is a massive hack after all), so you're doing better than me on that front.



> Any ideas on what can be done to fix this with NetworkManager applet? Am I missing something?

@NickHu See

- https://github.com/NixOS/nixpkgs/issues/43836
- https://github.com/taffybar/taffybar/issues/332#issuecomment-394804090 

Are you making sure to set GDK_PIXBUF_ICON_LOADER?

**Comment by NickHu** [comment]
@IvanMalison Indeed `GDK_PIXBUF_ICON_LOADER` is not set; I tried Googling for it but couldn't figure out what it's supposed to be set to. Is there any documentation somewhere?

**Comment by IvanMalison** [comment]
@NickHu On nixos you can set something like:

```
GDK_PIXBUF_MODULE_FILE = "${pkgs.librsvg.out}/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache";
```

**Comment by NickHu** [comment]
@IvanMalison Yes, I do have `GDK_PIXBUF_MODULE_FILE` set, but not `GDK_PIXBUF_ICON_LOADER` - it's strange because it seems to work fine on my other laptop; the only difference is that I just did a fresh install on my new laptop (where it's not working). Maybe there was a regression.

**Comment by IvanMalison** [comment]
@NickHu do you install things into your user? do you ahve hicolor theme installed?

**Comment by NickHu** [comment]
@IvanMalison I've tried it with just system, and when that didn't work I tried installing it as a user package too which also didn't work

**Comment by NickHu** [comment]
@IvanMalison I'm now thinking that this behaviour is not isolated to NetworkManager applet, but everything that uses libappindicator - I've filed a new issue against it

**Comment by PierreR** [comment]
Yep I have encountered this issue with Albert not having its icon anymore in the theme I am using. I don't use any fancy applet (my Taffybar config is minimal)

**Comment by purefn** [comment]
I was running into this issue with evince. The workaround worked in my case, but it took me several days to realize that's what was causing taffybar to crash.

**Comment by rvl** [comment]
I am using the `xsession` and `services.taffybar` modules from Nix **home-manager** and was getting these crashes.
The NixOS module setting which stopped the crashes for me was:
```
{ pkgs, ... }: {
  # excerpt of my config:
  home-manager.users.rodney = {
    xsession.enable = true;
    xsession.windowManager.xmonad.enable = true;
    services.taffybar.enable = true;
  };

  # Workaround https://github.com/taffybar/taffybar/issues/403
  # 1. Causes GDK_PIXBUF_MODULE_FILE to be set in xsession.
  services.xserver.gdk-pixbuf.modulePackages = [ pkgs.librsvg ];
  # 2. Generates caches for install icons
  gtk.iconCache.enable = true;
}
```
You will need to log out of your xsession to see the changes take effect.
This is because the `systemctl --user import-environment GDK_PIXBUF_MODULE_FILE` command is run early in the `~/.xsession` script.

**Comment by kurnevsky** [comment]
Here how I solved it: https://github.com/kurnevsky/dotfiles/blob/b3ad2b4d95e4e4ea089a337fe0da5317593d9a63/.config/taffybar/taffybar.hs#L75-L90

**Comment by IvanMalison** [comment]
> @IvanMalison should I make a PR to include it to taffybar? :)

@kurnevsky Yeah, that seems like a good change, please do

**Comment by nomeata** [comment]
JFTR; If you are using the work-around by @rvl, namely
```
  # Workaround https://github.com/taffybar/taffybar/issues/403
  # 1. Causes GDK_PIXBUF_MODULE_FILE to be set in xsession.
  services.xserver.gdk-pixbuf.modulePackages = [ pkgs.librsvg ];
  # 2. Generates caches for install icons
  gtk.iconCache.enable = true;
```
but after my upgrade to nixpkgs 22.05 this crashes with
```
~ $ taffybar 
Launching custom binary /home/jojo/.cache/taffybar/taffybar-linux-x86_64


(taffybar-linux-x86_64:2192): Gtk-WARNING **: 17:32:32.481: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
taffybar-linux-x86_64: Failed to load /nix/store/cv48kxfz5f2iqlgf6vy72glnnld4vdhg-gnome-terminal-3.44.1/share/icons/hicolor/scalable/apps/org.gnome.Terminal.svg: Bildlader-Modul konnte nicht geladen werden: /nix/store/9mhif0b5hh5af1r2imk8bx2mp7mp5lkz-librsvg-2.54.1/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: /nix/store/z56jcx3j1gfyk4sv7g8iaan0ssbdkhz1-glibc-2.33-56/lib/libc.so.6: version `GLIBC_2.34' not found (required by /nix/store/9mhif0b5hh5af1r2imk8bx2mp7mp5lkz-librsvg-2.54.1/lib/librsvg-2.so.2) (5)
```
simply recompile taffybar.
