### ISSUE TITLE
SNI icons that provide the empty string as an IconName cause crashes

### ISSUE THREAD

**Issue by IvanMalison** [taffybar/taffybar#404]
Steam does this, and causes taffybar to crash

**Comment by mimi1vx** [comment]
another example is https://remmina.org/

**Comment by IvanMalison** [comment]
@mimi1vx @MagicCloud can either of you verify that the issue is fixed on master/with gtk-sni-tray 0.1.5.0?

**Comment by Magicloud** [comment]
Seems fixed. Thanks.
