### ISSUE TITLE
Configurable features by cabal build flags

### ISSUE THREAD

**Issue by mimi1vx** [taffybar/taffybar#405]
Make taffybar features and deps configurable like xmobar:D

By default left all features enabled but can request disabling it. And disabled for experimental features.

for example I don't use any MPRIS2 compactible player + tray and CPU widget, but need experimental iw based wifi widget:

`cabal configure -f -SNITray -f MPRIS2 -f -CPU -f iwwifi`

and thanks to this build lighter bar without unneeded code

**Comment by IvanMalison** [comment]
@mimi1vx You can use the taffybar.hs file to configure which widgets are present.

I'm a bit wary of adding feature flags to get around the dependencies issue because i think that will make packaging for distros and installation a lot more complicated.

What would this buy us?

**Comment by mimi1vx** [comment]
> @mimi1vx You can use the taffybar.hs file to configure which widgets are present. 

this is different thing

In reality, it simplifies live of distros.. Any distribution packager knows how to work with build Flags

and for example, we used "xmobar" build flags to build xmobar-0.26.x with LTS-12  without dbus and hinotify...

**Comment by IvanMalison** [comment]
What dependency are we trying to avoid in this case?

**Comment by LeifW** [comment]
Another option would be to have a core taffybar lib, and have monitors that
add extra deps be in other package(s), a la xmonad-extras.

**Comment by IvanMalison** [comment]
I'm closing this because I just don't think it makes sense for taffybar.
