### ISSUE TITLE
Automatic documentation deployment to hackage/or at least automatic generation of documentation from master

### ISSUE THREAD

**Issue by mgttlinger** [taffybar/taffybar#406]
Since release 2.1.2, there is no API documentation for taffybar on hackage. Previous versions had their documentation uploaded by the maintainer.

**Describe the solution you'd like**
If possible it would be good if the documentation gets published to hackage along with the release in an automated fashion.

**Comment by IvanMalison** [comment]
@mgttlinger Yes, agreed. I think I just forgot to do it with 3.0.0. I'll try to update the documentation today.

Contributions are always welcome!

**Comment by anarcat** [comment]
ping? how can we help updating the docs here? is this related to #316?

**Comment by IvanMalison** [comment]
@anarcat Unfortunately, I need to do this because it requires access to hackage for taffybar. I'll need to encrypt a set of credentials to auto upload.

I suppose that if you could make a travis ci build that builds the haddocks (without necessarily uploading them) that could be helpful

**Comment by IvanMalison** [comment]
@anarcat @mgttlinger 

I've uploaded documentation for the latest version. This is probably the most usefule page:

http://hackage.haskell.org/package/taffybar-3.1.1/docs/System-Taffybar-Widget.html

**Comment by IvanMalison** [comment]
We'll need to do #434 first.

**Comment by IvanMalison** [comment]
This should be pretty easy now that #434 is done.

**Comment by IvanMalison** [comment]
@mgttlinger The new taffybar version has documentation. I don't think I'm ever going to go through the effort to make it totally automatic but it is pretty easy to do now with nix.

```
nix-shell --attr env
cabal new-haddock --haddock-for-hackage
cabal upload -d ./dist-newstyle/taffybar-3.2.0-docs.tar.gz 
```
