### ISSUE TITLE
Padding issues with workspaces

### ISSUE THREAD

**Issue by qrilka** [taffybar/taffybar#411]
**NOTE: If your issue is really a support request, please use the gitter channel to ask it instead of filing an issue https://gitter.im/taffybar/Lobby (REMOVE THIS IF NOT).**

**Describe the bug**
It appears that styling in workspaces widget gives extra padding and the default font is too large, e.g. see https://i.imgur.com/i5OFpD5.png - I have used the default config and removed `barHeight` (with it that padding is even more worse)
After setting the font to the default 10pt (for `.workspace-label`) I still get extra padding below CPU meter and I could get rid of it by setting `padding-bottom` and `padding-top` to 4px in `.inner-pad`

**To Reproduce**

Start  `taffybar` with the config from `taffybar.hs.example` with not predefined bar height

**Expected behavior**
Slick `taffybar` with not extra spaces between the bar and my xmonad workspaces.

**Screenshots**
See the link above

**Version information**
Taffybar version (or git sha if building from source): 3.0.0
Installation method (nix/stack/cabal/arch packages): emerge from gentoo-haskell
Gtk version: x11-libs/gtk+-3.22.30

**Comment by IvanMalison** [comment]
Isn't this just #270

**Comment by qrilka** [comment]
@IvanMalison probably it is as this one looks the way I tried to solve it 1st time:
> I have a similar issue when upgrading to the GTK3 version; I had to set barHeight = 35 in defaultTaffybarConfig to keep the bottom of graph widgets from being cut off.
