### ISSUE TITLE
Window title moves end widgets off screen

### ISSUE THREAD

**Issue by qrilka** [taffybar/taffybar#412]
**Describe the bug**
It appears that window title label has no width limit so if it gets too long then it moves end widgets far that the screen width so they get hidden. Not sure if a screenshot matters here but there's one I get - https://imgur.com/a/AonJLsy (normally I have weather widget, cpu meter and date/time)

**To Reproduce**
open window with very long title

**Expected behavior**
window title gets cut so the widgets declared in `endWidgets` keep being visible

**Screenshots**
https://imgur.com/a/AonJLsy

**Version information**

```
$ taffybar --version
taffybar 3.0.0
```

**Comment by IvanMalison** [comment]
You can limit the length of the window with

https://github.com/taffybar/taffybar/blob/09c600cdc1332619087a90c3958d5d1fd68a6067/src/System/Taffybar/Widget/Windows.hs#L49

This is not the default because different people might want different sorts of truncation.

**Comment by IvanMalison** [comment]
Yes.
