### ISSUE TITLE
Simple Command Button Widget

### ISSUE THREAD

**Issue by nomeata** [taffybar/taffybar#420]
I want to add a button to my taffybar that simply executes a command (in my case, to rotate the screen). I am surprised that there is no readily available widget for that – `System.Taffybar.Widget.CommandRunner` sounded promising, but is something different.

Expecting a type signature like
```
simpleButton :: MonadIO m
  => String --  Command to execute. Should be in $PATH or an absolute path
  -> String -- Label for the button
  -> m Widget
```

**Comment by IvanMalison** [comment]
@nomeata Seems reasonable, and quite easy, actually.

You should be able to reuse a bunch of the functions that run an executable.
