### ISSUE TITLE
Possible to switch to gi-cairo?

### ISSUE THREAD

**Issue by Magicloud** [taffybar/taffybar#423]
**Describe the solution you'd like**

ghc 8.6.1 has been released for a while, but latest cairo is still not buildable against it. So right now, when I build taffybar with cabal-install, it tries cairo-0.13.1.1, which contains problems to build as well.

Just saw that haskell-gi has a cairo binding, and I did not see cairo as a dependency of gi-cairo.

Is it possible to switch?

**Comment by IvanMalison** [comment]
hmm popssibly yes, but i have a vague recollection that something we need isnt supported

**Comment by Magicloud** [comment]
I was too young, too simple. Just got time and checked that gi-cairo is the binding of cairo, more likely just an interface.

**Comment by Magicloud** [comment]
I think the replacement can be done via gi-cairo-render and gi-cairo-connector packages, which are not in hackage yet.
Also a few other packages are unbuildable. Working on fixing....

**Comment by Magicloud** [comment]
I think things are simpler now. haskell-gi seems imported gi-cairo-render. But not quite done, I think.

**Comment by IvanMalison** [comment]
@Magicloud so this issue:

https://github.com/haskell-gi/haskell-gi/wiki/Using-Cairo-with-haskell-gi-generated-bindings

has been resolved?

**Comment by IvanMalison** [comment]
So i guess you are refering to cohomology/gi-cairo-render#1

**Comment by IvanMalison** [comment]
I'm going to go ahead and upload it to hackage

**Comment by Magicloud** [comment]
Thanks. Actually, there are some issues with gi-cairo-render, I think. The types are not the same thing with haskell-gi. And memory issue, I did not see reference/destroy being used as Cairo doc asked.
