### ISSUE TITLE
Add a nix travis build

### ISSUE THREAD

**Issue by IvanMalison** [taffybar/taffybar#434]

**Comment by mgttlinger** [comment]
Is there a technical reason for that or just preference? (I don't want to criticize. I'm a happy NIxOS user. Just curious)

**Comment by IvanMalison** [comment]
@mgttlinger 
The docker images that we use need to have all dependencies preinstalled (or else the build will take too long and travis will time out). This has to be done manually, and the build image ends up being huge (over a GB) so it wouldnt be practical to try to upload a new version every time a build succeeds.

Nix has a better solution to this (individually caching the build outputs of each package).

I'm open to suggestions on this front, but I just honestly find Docker to be kind of a bad way to go here.

**Comment by wizzup** [comment]
I would love to help on this but it seem current `default.nix` is unable to build.

If nix expression is buildable, getting a [cachix](https://cachix.org/) host could be benefit to all nix users.

```
[wizzup@ taffybar](master)$ git rev-parse HEAD
d4f983fe3f6ab1278aed1cc884b5afbcf1f4415d
[wizzup@ taffybar](master)$ nix-build
error: anonymous function at /nix/store/882yjym9xngn73c2liqy0yx6kjjzvw0j-cabal2nix-taffybar/default.nix:1:1 called without required argument 'gi-cairo-connector', at /nix/store/0l9hg9gg5bgn5ky4bkf95wlsdny7792k-source/pkgs/development/haskell-modules/make-package-set.nix:88:27
```

**Comment by IvanMalison** [comment]
@wizzup default.nix now builds, would love some help here.
