### ISSUE TITLE
Fails to compile against gi-gdkpixbuf 2.0.18 on nixpkgs

### ISSUE THREAD

**Issue by mdorman** [taffybar/taffybar#435]
**Describe the bug**

Compilation fails with:

```
[46 of 62] Compiling System.Taffybar.Information.Chrome ( src/System/Taffybar/Information/Chrome.hs, dist/build/System/Taffybar/Information/Chrome.o )

src/System/Taffybar/Information/Chrome.hs:66:32: error:
    • Couldn't match expected type ‘Gdk.Pixbuf’
                  with actual type ‘Maybe Gdk.Pixbuf’
    • In the ‘tabImageData’ field of a record
      In the expression:
        ChromeTabImageData {tabImageData = pixbuf, tabImageDataId = tabID}
      In an equation for ‘chromeTabImageData’:
          chromeTabImageData
            = ChromeTabImageData
                {tabImageData = pixbuf, tabImageDataId = tabID}
   |
66 |               { tabImageData = pixbuf
   |                                ^^^^^^
```

**To Reproduce**

Attempted to build taffybar-3.1.1 against nixpkgs/HEAD + nixpkgs/haskell-updates

**Expected behavior**

Successful compilation. :smile:

**Comment by IvanMalison** [comment]
Hmm. So it looks like there was a change to the interface (probably because an annotation was added):

http://hackage.haskell.org/package/gi-gdkpixbuf-2.0.16/docs/GI-GdkPixbuf-Objects-PixbufLoader.html#v:pixbufLoaderGetPixbuf

We currently build against gi-gdkpixbuf-2.0.16, so I guess we would need a version bound.

**Comment by IvanMalison** [comment]
@mdorman Any chance you can confirm that what is currently on master resolves this issue for you?

**Comment by mdorman** [comment]
Not until the weekend, but I will enthusiastically check then!

**Comment by mdorman** [comment]
Worked great!

**Comment by IvanMalison** [comment]
@mdorman Great. I'll upload a new version!

**Comment by MuratOzsoyler** [comment]
Has the new version been loaded? Still getting the same error.

**Comment by IvanMalison** [comment]
@MuratOzsoyler taffybar needs a new release, but if you compile against master, things hsould work just fine!

**Comment by MuratOzsoyler** [comment]
Thank you for replying. I  am in the process of installing NixOs and tried
to use taffybar. If new version is not ready I can wait for a while....

Regards,

Murat Özsöyler

Ivan Malison <notifications@github.com>, 9 Şub 2019 Cmt, 00:38 tarihinde
şunu yazdı:

**Comment by IvanMalison** [comment]
@mdorman @MuratOzsoyler A new version that fixes this has been released. Let me know if there are any further issues.
