### ISSUE TITLE
HTTP fails to get weather using HTTPS

### ISSUE THREAD

**Issue by qrilka** [taffybar/taffybar#438]
**Describe the bug**
Weather widget uses `HTTP` library to get weather information but  http://tgftp.nws.noaa.gov redirects to https://tgftp.nws.noaa.gov and `HTTP` can't handle HTTPS so no weather gets retrieved

**To Reproduce**
Use weather widget

**Expected behavior**
Weather information gets retrieved and displayed

**Version information**
Taffybar version (or git sha if building from source): 3.0.0
Installation method (nix/stack/cabal/arch packages): gentoo-haskell
Gtk version:

Locally I have monkey-patched code to use `http-client-tls` if it's OK to add that dependency I could create a PR to use that lib.

**Comment by IvanMalison** [comment]
> Locally I have monkey-patched code to use `http-client-tls` if it's OK to add that dependency I could create a PR to use that lib.

@qrilka A PR would be greatly appreciated.
