### ISSUE TITLE
upowerd change registration very wasteful

### ISSUE THREAD

**Issue by bgamari** [taffybar/taffybar#445]
**Describe the bug**

Currently `System.Taffybar.Information.Battery.registerForAnyUPowerPropertiesChanged` registers to be notified of any change in any properties. This essentially means that taffybar will be triggered to update every time upowerd polls not only because the battery is constantly changing charge state but also because changing system load means that the time-to-empty projection will essentially never be constant.

It seems to me like we should rather just poll with a fixed 10 or 30 second period. I wonder what gnome-shell, et al. do hre.

**Version information**
Taffybar version (or git sha if building from source): 4061bc7cdebb60885f927091e82932b8f107f4e4
Installation method (nix/stack/cabal/arch packages): Nix
Gtk version:

**Comment by IvanMalison** [comment]
@bgamari I've changed things so that by default we will only actually do updates if any of these properties are updated.

``` haskell
[ "IconName", "State", "Percentage" ]
```

Users can tweak which properties cause updates by calling `setupDisplayBatteryChanVar` with their own list of properties and running that as a hook i.e.:

```
startTaffybar $
  appendHook (setupDisplayBatteryChanVar ["Percentage"])
...
```

**Comment by bgamari** [comment]
Great, thanks!
