### ISSUE TITLE
nix build results in executable missing libgtk-3.s.o

### ISSUE THREAD

**Issue by chrissound** [taffybar/taffybar#461]
Just did a `nix build` of the master branch.

```
result/bin/taffybar 
Launching custom binary /home/chris/.cache/taffybar/taffybar-linux-x86_64

/home/chris/.cache/taffybar/taffybar-linux-x86_64: error while loading shared libraries: libgtk-3.so.0: cannot open shared object file: No such file or directory
```

Seems like we're not specifying all the dependencies?

**Comment by IvanMalison** [comment]
@chrissound Notice that taffybar is launching the taffybar from your cache directory. This is likely because you have a taffybar setup that uses `dyreTaffybar`. When taffybar uses dyreTaffybar it actually recompiles your config and reexecs as a different process.

I suspect that one of two things is happening here:

- You had already previously compiled taffybar, and the dyre is not recompiling here because you dont have any updates to your actual taffybar config.
- `dyreTaffybar` just doesn't quite work with nix because the binary it creates doesn't inherit all of the dependencies properly.

**Comment by IvanMalison** [comment]
The taffybar build for nixpkgs does this:

https://github.com/nixos/nixpkgs/blob/22a765d0da7070311e5b8c2bb29fa496c833dae5/pkgs/applications/window-managers/taffybar/default.nix#L12

which is likely to handle the issue I am describing.

The nix files in this repo are mostly for:

- Continuous integration builds
- People who want to write a nix derivation for their own taffybar binary and avoid `dyreTaffybar` all together

**Comment by chrissound** [comment]
Ah yes I think I've tried to run it before with stack - but didn't have luck with that either iirc.

I'm not too familiar with Nix on how that derivation works, but I'll take a look once I have time again (I assume you want me to pay attention the the wrapper as it's setting NIX_GHC?

I've also tried to install this via nixpkgs / nixos as a system package but that also runs into an error of:
```
taffybar                 
Error: 
/home/chris/.config/taffybar/taffybar.hs:5:1: error:
    Could not find module ‘System.Taffybar’
    Use -v to see a list of the files searched for.
  |
5 | import System.Taffybar
  | ^^^^^^^^^^^^^^^^^^^^^^

/home/chris/.config/taffybar/taffybar.hs:6:1: error:
    Could not find module ‘System.Taffybar.Hooks’
    Use -v to see a list of the files searched for.
  |
6 | import System.Taffybar.Hooks
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

/home/chris/.config/taffybar/taffybar.hs:7:1: error:
    Could not find module ‘System.Taffybar.Information.CPU’
    Use -v to see a list of the files searched for.
  |
7 | import System.Taffybar.Information.CPU
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

/home/chris/.config/taffybar/taffybar.hs:8:1: error:
    Could not find module ‘System.Taffybar.Information.Memory’
    Use -v to see a list of the files searched for.
  |
8 | import System.Taffybar.Information.Memory
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

/home/chris/.config/taffybar/taffybar.hs:9:1: error:
    Could not find module ‘System.Taffybar.SimpleConfig’
    Use -v to see a list of the files searched for.
  |
9 | import System.Taffybar.SimpleConfig
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

/home/chris/.config/taffybar/taffybar.hs:10:1: error:
    Could not find module ‘System.Taffybar.Widget’
    Use -v to see a list of the files searched for.
   |
10 | import System.Taffybar.Widget
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

/home/chris/.config/taffybar/taffybar.hs:11:1: error:
    Could not find module ‘System.Taffybar.Widget.Generic.PollingGraph’
    Use -v to see a list of the files searched for.
   |
11 | import System.Taffybar.Widget.Generic.PollingGraph
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

/home/chris/.config/taffybar/taffybar.hs:12:1: error:
    Could not find module ‘System.Taffybar.Widget.Generic.PollingLabel’
    Use -v to see a list of the files searched for.
   |
12 | import System.Taffybar.Widget.Generic.PollingLabel
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

/home/chris/.config/taffybar/taffybar.hs:13:1: error:
    Could not find module ‘System.Taffybar.Widget.Util’
    Use -v to see a list of the files searched for.
   |
13 | import System.Taffybar.Widget.Util
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

/home/chris/.config/taffybar/taffybar.hs:14:1: error:
    Could not find module ‘System.Taffybar.Widget.Workspaces’
    Use -v to see a list of the files searched for.
   |
14 | import System.Taffybar.Widget.Workspaces
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

 ✘  
```

Though that directory does not exist as I deleted it to be sure:
```
ls -altr /home/chris/.config/taffybar/           
ls: cannot access '/home/chris/.config/taffybar/': No such file or directory
```

**Comment by IvanMalison** [comment]
@chrissound Yes, if you tried to install it as a system package and then simply use the binary that is exactly what you would expect would happen. This is why you need to use the module provided in nixpkgs (because taffybar does dynamic recompilation it needs access to taffybar as a library not just an executable)

if you need more help with getting things running, feel free to chat in https://gitter.im/taffybar/Lobby

**Comment by chrissound** [comment]
Thank you for your help!
