### ISSUE TITLE
Split off pagerHints into a seperate installable.

### ISSUE THREAD

**Issue by LeifW** [taffybar/taffybar#480]
Feature  request: Split off System.Taffybar.Hooks.PagerHints.pagerHints into a separately installable module.

To enable it to be used with an xmonad that was installed in a different way than Taffybar itself.
E.g. on Arch Linux, I wish to continue using the XMonad provided by system packages (which is dynamically linked), but I would like the option to install Taffybar by e.g. cabal new-build or stack or whatever, and still have pagerHints available to call from my XMonad config.

I see that file just depends on XMonad and utf8-string, so that would be simple enough to install alongside the system-proved XMonad.

**Comment by IvanMalison** [comment]
I've actually been planning to do this for a while. To be honest, I think the best solution may be to simply add the Taffybar Pager hints module to xmonad-contrib. There is actually nothing in that file that depends on anything else in taffybar, and the exported pager hints could also be useful to non-taffybar status bars.

**Comment by IvanMalison** [comment]
Made https://github.com/xmonad/xmonad-contrib/pull/579

**Comment by IvanMalison** [comment]
xmonad-contrib module is merged, but not yet released. I guess we should wait for release to actually deprecate the existing module.
