### ISSUE TITLE
What is the idea of removing initialString parameter from System.Taffybar.Widget.Generic.PollingLabel?

### ISSUE THREAD

**Issue by qrilka** [taffybar/taffybar#481]
In e82b88d4c802c81175ce3c39d076823b3a7e21ea `initialString` argument was removed both from `pollingLabelNew` and `pollingLabelNewWithTooltipSource.
And the code using it was changed from
```
    label <- labelNew $ Just initialString
```
to
```
    label <- labelNew Nothing
```
was there some motivation to do this or maybe it was just some miss?
BTW also haddocks now are out of sync with the code.

**Comment by IvanMalison** [comment]
@qrilka What's the argument for its existence? We can just run the label one time initially to get the first text right?

**Comment by qrilka** [comment]
I don't think I understand your question completely.
The argument sets label when polling didn't give you any value yet. And this could easily happen e.g. when there are some connectivity problems or some similar issue like that, having some explicit text like "N/A" makes perfect sense in my opinion.

**Comment by IvanMalison** [comment]
@qrlika if connectivity fails, whatever your command is should fail and you can set text appropriately within the supplies io action.

The only case where I can imagine the initial text even remotely making sense is if you have some sort of long running call in your polling label. Even in that case though, it is easy enough to create an io action that quickly returns text the first time it is called, and then subsequently does whatever you actually want it to do.

My opinion is that the case where your poll operation is not quick enough to return immediately is rare enough that we should not clutter the interface just to accommodate this special case, when it is easy enough to get the same behavior by embedding it in the action.

**Comment by qrilka** [comment]
I think the new API is less intuitive, requires some stateful logic and is not documented.
I'm OK with you closing the issue if you disagree.

**Comment by IvanMalison** [comment]
@qrilka I mean its easy enough to make a helper to have the behavior that you want. I just think that for most cases, people will not care about having some special initial text.
