### ISSUE TITLE
FBReader.desktop: hGetContents: invalid argument (invalid byte sequence)

### ISSUE THREAD

**Issue by kurnevsky** [taffybar/taffybar#485]
**Describe the bug**
taffybar fails to launch and writes:
```
taffybar: /usr/share/applications/FBReader.desktop: hGetContents: invalid argument (invalid byte sequence)
```
I'm not actually sure it's the reason it doesn't start (I just installed it with nix and there might be some incompatibilities) but it worth to fix this error anyway.
FBreader is installed as arch package: https://www.archlinux.org/packages/community/x86_64/fbreader/

[FBReader.desktop.txt](https://github.com/taffybar/taffybar/files/4330266/FBReader.desktop.txt)

**To Reproduce**
Just launch it on arch linux with FBreader installed.

**Version information**
taffybar 3.2.2

**Comment by IvanMalison** [comment]
@kurnevsky you can fix this issue for now by using the ewmh Icon instead of using desktop files.
