### ISSUE TITLE
Stack install fails

### ISSUE THREAD

**Issue by quarkQuark** [taffybar/taffybar#487]
**Describe the bug**
Installing taffybar with stack fails, giving errors with extra-deps. Following the 'Recommended action' given in the command output (changing version numbers in extra-deps in stack.yaml) does not help: new errors are given with a recommended action that conflicts with the original action.
Replacing the default stack.yaml with example/stack.yaml does not help, as this only gives syntax errors.

**To Reproduce**
`git clone https://github.com/taffybar/taffybar.git taffybar-git`
`cd taffybar-git`
`stack install`

**Expected behavior**
Taffybar should be installed by stack with no errors
Unless I'm misunderstanding how to use stack, which is very possible as I am very inexperienced with stack. In that case there should probably be a clarification in the relevant part of the README.

**Version information**
Taffybar version (or git sha if building from source): 563fb5e3995e340b814be331ad111dafc1ccfc06
Installation method (nix/stack/cabal/arch packages): stack
Gtk version: gtk2 version 2.24.32-2, gtk3 version 1:3.24.16-1

**Comment by prietus** [comment]
same issue here, I'm not able to build it either using stack or cabal install, it always fails the same:
Failed to build gi-cairo-render-0.0.1.
Build log (
/home/teraflops/.cabal/logs/ghc-8.10.1/gi-cairo-render-0.0.1-270efc8e4135bc717d35d87489c89ab9756e5cdfb4ecf90304e5b6fca5860a46.log
):
Configuring library for gi-cairo-render-0.0.1..
Preprocessing library for gi-cairo-render-0.0.1..
c2hs: Prelude.head: empty list
cabal: Failed to build gi-cairo-render-0.0.1 (which is required by
exe:taffybar from taffybar-3.2.2). See the build log above for details.

270efc8e4135bc717d35d87489c89ab9756e5cdfb4ecf90304e5b6fca5860a46:
Configuring library for gi-cairo-render-0.0.1..
Preprocessing library for gi-cairo-render-0.0.1..
c2hs: Prelude.head: empty list

**Comment by IvanMalison** [comment]
@prietus I don't think your issue is the same as that of @quarkQuark .

I think what you are seeing may have something to do with missing gir files that are needed to generate the lib in question.

**Comment by IvanMalison** [comment]
@quarkQuark taffybar has now been included in the latest stack lts, will you try building again?

**Comment by quarkQuark** [comment]
It works now, thanks!
