### ISSUE TITLE
SNI secondary action

### ISSUE THREAD

**Issue by nomeata** [taffybar/taffybar#490]
According to the README of https://github.com/philipl/pidgin-indicator tray icons can have a “secondary action”, and it seems that most environment map middle mouse button click to it. As far as I can tell, the taffybar tray treats any click like a left click; it would be nice if the “other” clicks would do something.

Or maybe right-click should open the menu, and left click trigger the action? Up to you.

**Comment by IvanMalison** [comment]
See https://github.com/taffybar/gtk-sni-tray/issues/14
