### ISSUE TITLE
SNITray and libappindicator/libayatana-appindicator compatibility

### ISSUE THREAD

**Issue by NickHu** [taffybar/taffybar#491]
Recently I have been trying to move away from xembed/classic systray icons. To my surprise, everything I had been using actually supports AppIndicators when compiled with libappindicator/libayatana-appindicator (which seems to be a compatible library to supersede libappindicator), although nixpkgs does not yet do this (see the PRs below).

So after making them build with that library, I found that none of them were able to work properly with the SNITray widget, but curiously they all failed in the exact same manner - they produce no error output and seemingly don't show up in the tray. This reminded me of some behaviour I had encountered before with NetworkManager applet, as in #403. Upon closer examination, actually all the applications put something in the tray widget - including NetworkManager applet - on initialisation, but it seems like they get cleared instantaneously afterwards. This leads me to believe there is some sort of compatibility problem between Taffybar and libappindicator/libayatana-appindicator.

**Describe the bug**
AppIndicators (implemented by libappindicator/libayatana-appindicator) show up only briefly in the SNITray widget when their corresponding application is launched but then immediately disappear.

**To Reproduce**
Stare at the SNITray widget while running any of the following:
* https://github.com/NixOS/nixpkgs/pull/88784
* https://github.com/NixOS/nixpkgs/pull/88785
* https://github.com/NixOS/nixpkgs/pull/88786
* `nm-applet --indicator`

**Expected behavior**
AppIndicator icon stays in the tray widget

**Version information**
Taffybar version (or git sha if building from source):
Installation method (nix/stack/cabal/arch packages): nixos+home-manager
Gtk version:

**Comment by IvanMalison** [comment]
@NickHu nm-applet definitely works with the tray. Do you have a gtk-icon-theme set?

**Comment by NickHu** [comment]
@IvanMalison Ah indeed that was probably it!

Documenting the fix here for posterity:

I set

```
  gtk = {
    enable = true;
    iconTheme = {
      name = "Numix";
      package = pkgs.numix-icon-theme;
    };
    theme = {
      name = "NumixSolarizedDarkBlue";
      package = pkgs.numix-solarized-gtk-theme;
    };
  };
```

in my `home.nix`

and `services.dbus.packages = with pkgs; [ gnome3.dconf ];` in my `configuration.nix` (see https://github.com/rycee/home-manager/pull/510).

Perhaps this can still be considered a bug though, that the icons just disappear instead of showing some sort of no-icon-found placeholder.

**Comment by IvanMalison** [comment]
There's nothing that can be done on the gtk-sni-tray side.

**Comment by NickHu** [comment]
I suppose that makes sense. I'll try to submit a PR later to add some more documentation at the very least - I'm wondering if you have any suggestions for a quick distro-agnostic way to see if there is (say) an icon for nm-applet available? I'm not really familiar with GNOME or dconf

**Comment by IvanMalison** [comment]
@NickHu Not aware of anything off the top of my head. You can use d-feet to look up the information the SNI is broadcasting over dbus to see what the names of the icons it is looking for are. From there it shouldnt be too hard to look up whether a them has an icon. For most icons, however, this shouldnt be an issue as there should be an icon in the default theme.

**Comment by IvanMalison** [comment]
@NickHu Is this issue resolved?

**Comment by IvanMalison** [comment]
@NickHu ping.

Actually I just realized that this was partly about ayatana compatibility. Is that still an issue?

If not can we close this?
