### ISSUE TITLE
Update 'find your weather station' comment

### ISSUE THREAD

**Issue by MyriaCore** [taffybar/taffybar#493]
The code comments link to `https://www.weather.gov/tg/siteloc` to aid users in finding their stations:

https://github.com/taffybar/taffybar/blob/a1bec09a7dcc65490eac93163d8cdf55dd1c2cdd/src/System/Taffybar/Widget/Weather.hs#L2-L5

This site is outdated, and contains tons of dead links (such as the state lookup button, which redirects to `https://weather.noaa.gov/cgi-bin/nsd_state_lookup.pl`, which 404's). When doing my own research, I found [this page](https://cnrfc.noaa.gov/metar.php) to be much more helpful. I recommend at least linking this page alongside `https://www.weather.gov/tg/siteloc` in the comments. 

Something like this might be a bit more helpful:

```haskell
-- | This module defines a simple textual weather widget that polls 
-- NOAA for weather data.  To find your weather station, you can use 
-- either of the following:
-- 
-- <https://www.weather.gov/tg/siteloc> 
-- <https://cnrfc.noaa.gov/metar.php>
```

**Comment by IvanMalison** [comment]
PR welcome
