### ISSUE TITLE
Nix build does not work with the latest v3.2.2

### ISSUE THREAD

**Issue by PierreR** [taffybar/taffybar#503]
**Describe the bug**
Using the latest tagged version 'v3.2.2', `taffybar does not build with nix`.
It fails with
```
error: getting attributes of path '/home/vagrant/tmp/taffybar/xdg-desktop-entry.patch': No such file or directory
```

**To Reproduce**
cachix use taffybar
git clone https://github.com/taffybar/taffybar.git
git checkout v3.2.2
nix-build

**Expected behavior**
The build succeeds and retrieves `taffybar` from cachix without building anything.

**Version information**
git ref tag = v3.2.2
Installation method (nix/stack/cabal/arch packages): nix

**Extra notes**

`nix-build` works with the latest master 7f3b5bdc3711
Ideally I would like to hit a version that is in the cachix cache so I don't need to wait for the compilation step.

**Comment by IvanMalison** [comment]
This is fixed in v3.2.3
