### ISSUE TITLE
Workspaces: When maxIcons is 0, a white bar should be displayed underneath the workspace icon

### ISSUE THREAD

**Issue by MyriaCore** [taffybar/taffybar#504]
While I like the fact that the workspaces widget can show the currently-focused window in the workspace, I personally prefer that *only* the workspaces are shown. However, if I set `maxIcons = Just 0`, then there's no indication of what the active workspace is, since the little underline only displays under the window icons.

**Describe the solution you'd like**

When `maxIcons` is `Just 0`, the white bar should display underneath the workspace icon itself.

**Comment by IvanMalison** [comment]
@MyriaCore you should be able to get this effect by tweaking the taffybar css file.

There are lots of different types of effects you can use to indicate what you want, but they will generally all operate on the classes `.active .contents`. Here's an example:

```
.active .contents {
	background-color: rgba(1.0, 1.0, 1.0, 1.0);
}
```

If you want some ideas for how things can look let me know.

**Comment by MyriaCore** [comment]
Sure! I'll see if I can free up some time in the weekend to play around with that.

**Comment by IvanMalison** [comment]
@MyriaCore What do you mean by contextually?

**Comment by MyriaCore** [comment]
@IvanMalison Through the value of `maxIcons`, as the issue describes.

**Comment by IvanMalison** [comment]
The thing is that there are many different ways that you can indicate this sort of thing (bg color, underline, font color etc.) And I want to allow users the flexibility to choose how it looks.

**Comment by IvanMalison** [comment]
> I do think it'd be cool to contextually support this, though. In that sense, the css stuff is kinda more of a workaround.

@MyriaCore You could get contextual css support by adding a class for when the workspace is empty.

I do think that using css for workspaces is probably the way to go since styling things with wrappers and stuff can get pretty messy in haskell. I am open to PRs though.
