### ISSUE TITLE
Workspaces widget doesn't reduce width

### ISSUE THREAD

**Issue by kurnevsky** [taffybar/taffybar#506]
**Describe the bug**
Workspaces widget doesn't reduce width properly if window icons left/right padding is defined in css. Might be a leak somewhere.

**To Reproduce**
- Set `minIcons` to 0.
- Set `padding-right` and `padding-left` (e.g. 10px) to https://github.com/taffybar/taffybar/blob/d1246c40967abc848b5d7b4f9e69a14f898e995f/taffybar.css#L71
- Open some windows on empty workspace and close them.

**Expected behavior**
Workspace width should be reduced to 0, i.e. only workspace number should be displayed.

**Screenshots**
![screenshot-2020-12-08-10:30:14](https://user-images.githubusercontent.com/2943605/101455390-67ee1d00-392a-11eb-949d-b1e01c52ffd2.png)

**Version information**
Taffybar version (or git sha if building from source): 3.2.2
Installation method (nix/stack/cabal/arch packages): nixos 20.09
Gtk version: ?

**Comment by IvanMalison** [comment]
@kurnevsky This is an artifact of how the workspaces code avoids creating extra gtk objects. If you read the code closely it should be pretty obvious why its happening. You should be able to set css on another class to achieve a similar effect to avoid this issue though.

I agree that its not ideal but this would probably only get fixed if a workspaces refactor were to happen.

**Comment by kurnevsky** [comment]
ok, thanks. Then closing it in favor of https://github.com/taffybar/taffybar/issues/349
