### ISSUE TITLE
CHANGELOG missing for versions 3.2.2+

### ISSUE THREAD

**Issue by srid** [taffybar/taffybar#510]
Per Git tag, latest version is 3.2.5, yet CHANGELOG.md records changes only up to 3.2.2,

https://github.com/taffybar/taffybar/blob/v3.2.5/CHANGELOG.md

Permalink: https://github.com/taffybar/taffybar/blob/91c83e01e131d560e704b12f0d798905e4289a3d/CHANGELOG.md

**Comment by IvanMalison** [comment]
@srid Feel free to make one: Should be easy to reconstruct what was done from the commit messages https://github.com/taffybar/taffybar/compare/v3.2.2...master

**Comment by IvanMalison** [comment]
I added a changelog (although it doesn't include everything) for 3.3.0
