### ISSUE TITLE
ConfigFile -> MissingH dependency

### ISSUE THREAD

**Issue by jchia** [taffybar/taffybar#540]
One of the things blocking taffybar from being built with GHC 9.0 is the dependency on ConfigFile, which in turn depends on MissingH.

MissingH's last commit was in Apr 2020. I'm not sure if it's really maintained. ConfigFile is not on github, the last Hackage upload was in 2014 and the Hackage homepage link gives a HTTP 400, so I'm not sure whether ConfigFile is maintained either.

To reduce dependencies holding back taffybar, what about using another library for processing .ini files other than ConfigFile?

**Comment by IvanMalison** [comment]
@jchia Sorry I missed this. I think that taffybar does now compile with ghc 9.0.

I would definitely be open to getting rid of config file though.

Is this still an issue for you?
