### ISSUE TITLE
Support running multiple/different bar configurations

### ISSUE THREAD

**Issue by kwshi** [taffybar/taffybar#552]
Main proposal: add a CLI flag to taffybar's default launcher to customize which configuration to launch (instead of hardcoded `taffybar.hs`).

Here's my example use case. I want to run multiple bar instances with different definitions concurrently:
- the top bar contains a workspace switcher, window title
- the bottom bar contains widgets like brightness, volume, weather, CPU, FS monitor, etc., systray.
There's too many widgets to fit within a single bar (all on the top), so I like to have two separate bars.

(example view)
![image](https://user-images.githubusercontent.com/3887189/188396642-0d04bcea-57f7-4859-9bc1-3c08b81113e3.png)

Coming from polybar, this is easy to setup-- just define two bar configurations, then pass in the name of the bar config as argument when launching polybar.  However, taffybar [hardcodes launching from `$XDG_CONFIG_HOME/taffybar/taffybar.hs`](https://github.com/taffybar/taffybar/blob/945a08452660de603193da8d297d559fdca497d1/app/Main.hs#L46), making it impossible to have different definitions and choose different ones to launch.

This is already sort of possible with taffybar, but it's not very convenient: I could just compile & launch the non-default taffybar instance manually from a different location (requires manually invoking `ghc` or `stack`, no support for change-detection and auto-recompile).  What I'm really looking for is native launching support (via dyre), with automatic change-detection and recompiling, and launching directly via the `taffybar` command instead of a separately-installed executable.

I propose adding some optional, backwards-compatible CLI flag to the main taffybar executable, such as `--config-main`, to be used as:
```bash
taffybar --config-main=taffybar-alt.hs
```
(where the current/default behavior when the argument is omitted is equivalent to passing `--config-main=taffybar.hs`), which customizes which taffybar configuration to launch via dyre.

---

To be clear, this is _different_ from https://github.com/taffybar/taffybar/issues/139, which (based on my understanding) seems to be about running multiple instances of the _same_ bar on multiple monitors.  My request is about choosing different bars to run at the same time, independent of multi-monitor setups.

**Comment by kwshi** [comment]
On further inspection, if this were to be implemented, it would have to be slightly more complicated than simply passing a CLI argument to `taffybar`-- the bar executable itself needs to also know where to find its own source to recompile.  So one would have to customize the default `dyreTaffybar` arguments, something like this:

```haskell
import qualified Config.Dyre as Dyre
import System.Taffybar

dyreTaffybar :: TaffybarConfig -> IO ()
dyreTaffybarAlt = Dyre.wrapMain $ taffybarDyreParams { Dyre.projectName = "taffybar-alt" }
```
Another caveat to this is that Dyre seems to be designed with only single instances in mind-- this approach would require the two configurations to be located in different _folders_ as well: one under `$XDG_CONFIG_HOME/taffybar/taffybar.hs`, the other at `$XDG_CONFIG_HOME/taffybar-alt/taffybar-alt.hs`.  This isn't totally a dealbreaker, but it's not very ergonomic and also makes it harder to reuse helper code across the two configurations.

**Comment by purefn** [comment]
Why not just use an environment variable to decide which configuration to use?

**Comment by IvanMalison** [comment]
@kwshi This is already supported, through the more advanced bar configuration interface (BarConfigGetter on Context). I don't think that having multiple taffybar processes is a good approach anyway.

Basically the way you use it is by writing a taffybar io action that returns a List of BarConfigs. This interface is admittedly complex and perhaps somewhat difficult to use but it allows a lot of flexibility.

**Comment by IvanMalison** [comment]
Also @purefn 's suggestion would also work for something like what you want.

**Comment by IvanMalison** [comment]
> However, taffybar [hardcodes launching from `$XDG_CONFIG_HOME/taffybar/taffybar.hs`](https://github.com/taffybar/taffybar/blob/945a08452660de603193da8d297d559fdca497d1/app/Main.hs#L46),

This is only true if you aren't use the project approach.

**Comment by kwshi** [comment]
Aha! I think I've figured out how to do it with the `BarConfigGetter` interface.  Here's a rough sketch of how I did it:
```haskell

-- bar unique ID (needed for passing into StrutConfig) -> monitor index -> configuration record
type BarDefinition = Data.Unique.Unique -> GHC.Int.Int32 -> BarConfig

bar1 :: BarDefinition
bar1 barId monitor =
  -- see <https://hackage.haskell.org/package/taffybar-3.3.0/docs/System-Taffybar-Context.html#t:BarConfig>
  defaultBarConfig
    { -- see <https://hackage.haskell.org/package/taffybar-3.3.0/docs/src/System.Taffybar.SimpleConfig.html#toStrutConfig>
      strutConfig = defaultStrutConfig { strutMonitor = Just monitor },
      startWidgets = [ {- stuff -} ],
      endWidgets = [ {- other stuff -} ],
      {- other overrides -}
    }

bar2 :: BarDefinition
bar2 = _ {- another definition -}

-- for displaying on all monitors, see <https://hackage.haskell.org/package/taffybar-3.3.0/docs/src/System.Taffybar.SimpleConfig.html#useAllMonitors>
getMonitors :: IO [GHC.Int.Int32]
getMonitors = do
  screen <- GI.Gdk.screenGetDefault
  monitorCount <-
    maybe (pure 0)
      (GI.Gdk.screenGetDisplay >=> GI.Gdk.displayGetNMonitors) screen
  pure [0 .. monitorCount - 1]

withIds :: BarDefinition -> [GHC.Int.Int32] -> IO [BarConfig
withIds defn = mapM (withId f)
  where
    withId f monitor = f <$> Data.Unique.newUnique <*> pure monitor

getBars :: IO [BarConfig]
getBars = do
  monitors <- getMonitors
  top <- withIds topBar monitors
  bottom <- withIds bottomBar monitors
  pure $ top <> bottom

main :: IO ()
main =
  dyreTaffybar $
    defaultTaffybarConfig
      { getBarConfigsParam = lift getBars }

```

By the way, I noticed that the existing `SimpleConfig` [makes use of MVars](https://hackage.haskell.org/package/taffybar-3.3.0/docs/src/System.Taffybar.SimpleConfig.html#toTaffyConfig) to generate multiple bar instances, but I can't tell/understand why that's necessary/how that achieves anything really different from a `List.map` (which is why I've defined my example above using only list fmaps).  My code above seems to work as expected for me; am I missing out on something/doing something wrong by not doing this with MVars?

**Comment by IvanMalison** [comment]
>  on second thought, maybe it has something to do with hotplug/unplugging monitors, and updating bar instances on-the-fly? I'm not sure.

Yes exactly. This was perhaps a misguided attempt to allow you to avoid recreating bars by giving them a unique Id. This bar config getter is really only called on initialization and when the monitor configuration changes. For what you want to do it shouldn't matter too much.

**Comment by IvanMalison** [comment]
>  on second thought, maybe it has something to do with hotplug/unplugging monitors, and updating bar instances on-the-fly? I'm not sure.

Yes exactly. This was perhaps a misguided attempt to allow you to avoid recreating bars by giving them a unique Id. This bar config getter is really only called on initialization and when the monitor configuration changes. For what you want to do it shouldn't matter too much.

**Comment by kwshi** [comment]
Wonderful, thanks so much!  I'll close this now.
