### ISSUE TITLE
Taffybar barHeight problem

### ISSUE THREAD

**Issue by Lanpingner** [taffybar/taffybar#557]
Good day to all of you

I am quite new to taffybar (installed today) and i am trying to setup barHeight but getting no luck

my taffybar.hs
`
Start taffybar.hs
-------------------------------------------------------------------------------------------------------
{-# LANGUAGE OverloadedStrings #-}
import Data.Default (def)
import System.Taffybar
import System.Taffybar.Context hiding (startWidgets, endWidgets, widgetSpacing)
import System.Taffybar.Hooks
import System.Taffybar.Information.CPU
import System.Taffybar.Information.CPU2
import System.Taffybar.Information.Memory
import System.Taffybar.SimpleConfig
import System.Taffybar.Widget
import System.Taffybar.Widget.Battery
import System.Taffybar.Widget.CommandRunner
import System.Taffybar.Widget.FreedesktopNotifications
import System.Taffybar.Widget.Generic.PollingGraph
import System.Taffybar.Widget.Generic.PollingLabel
import System.Taffybar.Widget.Text.NetworkMonitor
import System.Taffybar.Widget.Util
import System.Taffybar.Widget.Windows
import System.Taffybar.Widget.Workspaces

import qualified GI.Gtk as Gtk
import qualified Data.Text as T

data Resolution = HD | UHD
data Device     = Desktop | Laptop

cpuCallback = do
  (_, systemLoad, totalLoad) <- cpuLoad
  return [ totalLoad, systemLoad ]

main = do
  let cpuCfg = def
                 { graphDataColors = [ (0, 1, 0, 1), (1, 0, 1, 0.5)]
                 , graphLabel = Just "cpu"
                 }
      clock = textClockNewWith def
      cpu = pollingGraphNew cpuCfg 0.5 cpuCallback
      res  = HD
      workspaces = workspacesNew def
      startW = [ workspaces ]
      endW = [ sniTrayThatStartsWatcherEvenThoughThisIsABadWayToDoIt, clock, cpu]
      simpleConfig = defaultSimpleTaffyConfig 
                        { startWidgets  = startW
                          , endWidgets    = endW
                          , barHeight =  20
                          , barPosition   = Top
                          , widgetSpacing = 0
                        }
  dyreTaffybar $ toTaffyConfig simpleConfig

barSize :: Resolution -> Int
barSize HD  = 25
barSize UHD = 55

End taffybar.hs
-------------------------------------------------------------------------------------------------------
`

Start Error message
-------------------------------------------------------------------------------------------------------

but when i try to run taffybar, i am getting this error

   • No instance for (Num StrutSize) arising from the literal 20
    • In the ‘barHeight’ field of a record
      In the expression:
        defaultSimpleTaffyConfig
          {startWidgets = startW, endWidgets = endW, barHeight = 20,
           barPosition = Top, widgetSpacing = 0}
      In an equation for ‘simpleConfig’:
          simpleConfig
            = defaultSimpleTaffyConfig
                {startWidgets = startW, endWidgets = endW, barHeight = 20,
                 barPosition = Top, widgetSpacing = 0}
   |
45 |                           , barHeight =  20
   |                                          ^^

End Error message
-------------------------------------------------------------------------------------------------------

i don't know where to look for the answer, that why i wrote here 

Please help me, i am stuck

**Comment by IvanMalison** [comment]
@Lanpingner Look at the type of barHeight in SimpleConfig:

https://github.com/taffybar/taffybar/blob/8050417e576e6b5b6825132577a9d046efdd6b04/src/System/Taffybar/SimpleConfig.hs#L54

It needs to be something of type StrutSize which is defined here:

https://github.com/taffybar/gtk-strut/blob/d946eb230cdccf5afc063642b3215723e555990b/src/Graphics/UI/GIGtkStrut.hs#L37

changing to

```
barHeight = ExactSize 20
```

should fix your problem (assume ExactSize is in scope).

**Comment by IvanMalison** [comment]
@Lanpingner generally it's better to ask questions like this in the matrix/element/gutter chat. Creating an issue with taffybar is not really the right thing to do because the problem is with your config.
