### ISSUE TITLE
`SNITray` does not show the icons for applications that were launched before `taffybar`

### ISSUE THREAD

**Issue by arximboldi** [taffybar/taffybar#578]
**Describe the bug**

When you launch the `taffybar` command, if there were some applications that could use it already running, they are not shown. You have to launch `taffybar`, and then the application.

While this is not a deal-breaker, it is kind of annoying when re-starting XMonad or Taffybar for whatever reason during a session.

**Version information**
taffybar 4.0.2
installed via nixos-24.05

**Comment by colonelpanic8** [comment]
There's a reason why its called:

```
tray = sniTrayThatStartsWatcherEvenThoughThisIsABadWayToDoIt
```

https://github.com/taffybar/status-notifier-item provides a standalone watcher that is extremely stable that will remember registrations and avoid this problem.

**Comment by arximboldi** [comment]
Hi @colonelpanic8 !I actually was not using that function, but I just realized that my XMonad launch script was restarting `status-notifier-item` every time. Thank you a lot for the tip and sorry for the noise!

**Comment by colonelpanic8** [comment]
@arximboldi ah that makes sense. Yeah I'd recommend simply running it as a systemd service. I've been doing this for years and I think it has not even crashed literally once on me.

**Comment by colonelpanic8** [comment]
are you using home-manager? you can actually just add this to your config if you are:

https://github.com/colonelpanic8/dotfiles/blob/77fe614b7bda8c9c6af5b987395df7484351c444/nixos/xmonad.nix#L59

**Comment by arximboldi** [comment]
Oh that's nice! I haven't started using `home-manager` yet, but I am very tempted, particularly for the `systemd` support. I have a more manual way of managing dotfiles via GNU `stow` that predates my Nixification and haven't found the urgency to migrate just yet, but configurating taffybar there looks really sweet. Thanks for the tip!

**Comment by colonelpanic8** [comment]
> I have a more manual way of managing dotfiles via GNU `stow` that predates my Nixification and haven't found the urgency to migrate just yet

I have something similar for most of my dotfiles -- you don't have to switch everything over all at once; you can actually just go incrementally.
