### ISSUE TITLE
Don't just fail/hang when no config file can be found

### ISSUE THREAD

**Issue by Tarrasch** [taffybar/taffybar#60]
It's extremely confusing that the if the config file is missing or misspelled. The bar just starts blank. Leaving users clueless if there graphics driver is flawed or if taffybar really should start blank.

Instead it could display something like "Welcome to taffybar, configure at `$HOME/.config/taffybar/taffybar.hs`"

**Comment by IvanMalison** [comment]
cc @chrissound - Not sure if this is exactly what you had in mind, but i think this is reasonably close.
