### ISSUE TITLE
Current keyboard layout

### ISSUE THREAD

**Issue by jagajaga** [taffybar/taffybar#79]
Hello!
Do you have some ideas to implement widget showing current keyboard layout?
You can use https://github.com/aartamonau/haskell-x11-xkb or https://github.com/jaor/xmobar/blob/master/src/Plugins/Kbd.hsc
If I have time, I will try to implement myself.

**Comment by IvanMalison** [comment]
@zabbal does ktc have appindicator support?

**Comment by IvanMalison** [comment]
I agree with @zabbal, though. This seems like something that should be handled in an SNI icon to me.
